<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introdução à Linguagem R - 7&nbsp; Tidy Data: uma abordagem para organizar os seus dados com tidyr</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 1em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../Capítulos/08-ggplot.html" rel="next">
<link href="../Capítulos/06-dados-relacionais.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Capítulos/03-tidyverse.html">Importando, organizando e transformando dados</a></li><li class="breadcrumb-item"><a href="../Capítulos/07-tidy-data.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title"><em>Tidy Data</em>: uma abordagem para organizar os seus dados com <code>tidyr</code></span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Introdução à Linguagem R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefácio</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Introduzindo a Linguagem R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/01-nocoes-basicas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Noções Básicas do R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/02-fundamentos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fundamentos da Linguagem R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Importando, organizando e transformando dados</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/03-tidyverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduzindo o universo do <code>tidyverse</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/03-importacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Importando e exportando dados com <code>readr</code>, <code>readxl</code> e <code>haven</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/04-transformacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Transformando dados com <code>dplyr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/06-dados-relacionais.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introdução a base de dados relacionais com <code>dplyr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/07-tidy-data.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title"><em>Tidy Data</em>: uma abordagem para organizar os seus dados com <code>tidyr</code></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Visualizando seus dados</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/08-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Visualização de dados com <code>ggplot2</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/09-theme-ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Configurando componentes estéticos do gráfico no <code>ggplot2</code></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Ferramentas para tipos específicos de dados</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/10-strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Manipulação e transformação de <em>strings</em> com <code>stringr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/11-factors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Introduzindo fatores (<em>factor</em>’s) com <code>forcats</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/12-variaveis-tempo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Introdução à variáveis de tempo com <code>lubridate</code></span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Funções e Loops: construindo os seus próprios programas e automatizando tarefas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/13-controle-fluxo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Controle condicional de fluxo</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/05-funcoes-loops.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Funções</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/17-loops.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title"><em>Loops</em></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/18-purrr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title"><em>Functional programming</em> com <code>purrr</code></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/15-debugging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title"><em>Debugging</em> - Resolvendo <em>bugs</em> em suas funções</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/16-environments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title"><em>Environments</em> ou ambientes no R</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Apêndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercícios</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Capítulos/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referências bibliográficas</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#sec:chapter_tidy_data" id="toc-sec:chapter_tidy_data" class="nav-link active" data-scroll-target="#sec\:chapter_tidy_data"><span class="header-section-number">7.1</span> Introdução e pré-requisitos</a></li>
  <li><a href="#o-que-é-tidy-data" id="toc-o-que-é-tidy-data" class="nav-link" data-scroll-target="#o-que-é-tidy-data"><span class="header-section-number">7.2</span> O que é <em>tidy data</em>?</a>
  <ul class="collapse">
  <li><a href="#será-que-você-entendeu-o-que-é-tidy-data" id="toc-será-que-você-entendeu-o-que-é-tidy-data" class="nav-link" data-scroll-target="#será-que-você-entendeu-o-que-é-tidy-data"><span class="header-section-number">7.2.1</span> Será que você entendeu o que é tidy data?</a></li>
  <li><a href="#uma-breve-definição-de-formas" id="toc-uma-breve-definição-de-formas" class="nav-link" data-scroll-target="#uma-breve-definição-de-formas"><span class="header-section-number">7.2.2</span> Uma breve definição de formas</a></li>
  </ul></li>
  <li><a href="#operações-de-pivô" id="toc-operações-de-pivô" class="nav-link" data-scroll-target="#operações-de-pivô"><span class="header-section-number">7.3</span> Operações de pivô</a>
  <ul class="collapse">
  <li><a href="#adicionando-linhas-à-sua-tabela-com-pivot_longer" id="toc-adicionando-linhas-à-sua-tabela-com-pivot_longer" class="nav-link" data-scroll-target="#adicionando-linhas-à-sua-tabela-com-pivot_longer"><span class="header-section-number">7.3.1</span> Adicionando linhas à sua tabela com <code>pivot_longer()</code></a></li>
  <li><a href="#adicionando-colunas-à-sua-tabela-com-pivot_wider" id="toc-adicionando-colunas-à-sua-tabela-com-pivot_wider" class="nav-link" data-scroll-target="#adicionando-colunas-à-sua-tabela-com-pivot_wider"><span class="header-section-number">7.3.2</span> Adicionando colunas à sua tabela com <code>pivot_wider()</code></a></li>
  </ul></li>
  <li><a href="#trabalhando-com-dados-aninhados-ou-em-árvores-json-html-xml" id="toc-trabalhando-com-dados-aninhados-ou-em-árvores-json-html-xml" class="nav-link" data-scroll-target="#trabalhando-com-dados-aninhados-ou-em-árvores-json-html-xml"><span class="header-section-number">7.4</span> Trabalhando com dados aninhados ou em árvores (JSON, HTML, XML)</a>
  <ul class="collapse">
  <li><a href="#criando-colunas-a-partir-dos-atributos-da-lista" id="toc-criando-colunas-a-partir-dos-atributos-da-lista" class="nav-link" data-scroll-target="#criando-colunas-a-partir-dos-atributos-da-lista"><span class="header-section-number">7.4.1</span> Criando colunas a partir dos atributos da lista</a></li>
  <li><a href="#criando-linhas-a-partir-dos-atributos-da-lista" id="toc-criando-linhas-a-partir-dos-atributos-da-lista" class="nav-link" data-scroll-target="#criando-linhas-a-partir-dos-atributos-da-lista"><span class="header-section-number">7.4.2</span> Criando linhas a partir dos atributos da lista</a></li>
  <li><a href="#coletando-atributos-específicos-de-sua-lista" id="toc-coletando-atributos-específicos-de-sua-lista" class="nav-link" data-scroll-target="#coletando-atributos-específicos-de-sua-lista"><span class="header-section-number">7.4.3</span> Coletando atributos específicos de sua lista</a></li>
  </ul></li>
  <li><a href="#completando-e-expandindo-a-sua-tabela" id="toc-completando-e-expandindo-a-sua-tabela" class="nav-link" data-scroll-target="#completando-e-expandindo-a-sua-tabela"><span class="header-section-number">7.5</span> Completando e expandindo a sua tabela</a>
  <ul class="collapse">
  <li><a href="#encontrando-possíveis-combinações-com-a-função-expand" id="toc-encontrando-possíveis-combinações-com-a-função-expand" class="nav-link" data-scroll-target="#encontrando-possíveis-combinações-com-a-função-expand"><span class="header-section-number">7.5.1</span> Encontrando possíveis combinações com a função <code>expand()</code></a></li>
  <li><a href="#a-metodologia-por-detrás-do-processo" id="toc-a-metodologia-por-detrás-do-processo" class="nav-link" data-scroll-target="#a-metodologia-por-detrás-do-processo"><span class="header-section-number">7.5.2</span> A metodologia por detrás do processo</a></li>
  <li><a href="#a-função-complete-como-um-atalho-útil" id="toc-a-função-complete-como-um-atalho-útil" class="nav-link" data-scroll-target="#a-função-complete-como-um-atalho-útil"><span class="header-section-number">7.5.3</span> A função <code>complete()</code> como um atalho útil</a></li>
  </ul></li>
  <li><a href="#preenchendo-valores-não-disponíveis-na" id="toc-preenchendo-valores-não-disponíveis-na" class="nav-link" data-scroll-target="#preenchendo-valores-não-disponíveis-na"><span class="header-section-number">7.6</span> Preenchendo valores não-disponíveis (<code>NA</code>)</a>
  <ul class="collapse">
  <li><a href="#utilizando-se-de-valores-anteriores-ou-posteriores" id="toc-utilizando-se-de-valores-anteriores-ou-posteriores" class="nav-link" data-scroll-target="#utilizando-se-de-valores-anteriores-ou-posteriores"><span class="header-section-number">7.6.1</span> Utilizando-se de valores anteriores ou posteriores</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../Capítulos/03-tidyverse.html">Importando, organizando e transformando dados</a></li><li class="breadcrumb-item"><a href="../Capítulos/07-tidy-data.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title"><em>Tidy Data</em>: uma abordagem para organizar os seus dados com <code>tidyr</code></span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title"><em>Tidy Data</em>: uma abordagem para organizar os seus dados com <code>tidyr</code></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec:chapter_tidy_data" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="sec:chapter_tidy_data"><span class="header-section-number">7.1</span> Introdução e pré-requisitos</h2>
<p>Em qualquer análise, o formato no qual os seus dados se encontram, é muito importante. O que vamos discutir neste capítulo, será como reformatar as suas tabelas, corrigir valores não disponíveis, ou “vazios” que se encontram no formato incorreto, ou então, como preencher as suas colunas que estão incompletas de acordo com um certo padrão.</p>
<p>Você rapidamente descobre a importância que o formato de sua tabela carrega para o seu trabalho, na medida em que você possui pensamentos como: “Uhmm…se essa coluna estivesse na forma x, eu poderia simplesmente aplicar a função <code>y()</code> e todos os meus problemas estariam resolvidos”; ou então: “Se o Arnaldo não tivesse colocado os totais junto dos dados desagregados, eu não teria todo esse trabalho!”; ou talvez: “Qual é o sentido de colocar o nome dos países nas colunas? Assim fica muito mais difícil de acompanhar os meus dados!”.</p>
<p>Para corrigir o formato das nossas tabelas, vamos utilizar neste capítulo as funções do pacote <code>tidyr</code> que está incluso no <code>tidyverse</code>. Pelo próprio nome do pacote (<em>tidy</em>, que significa “arrumar”), já sabemos que ele inclui diversas funções que tem como propósito, organizar os seus dados. Portanto, lembre-se de chamar pelo pacote (seja pelo <em>tidyr</em> diretamente, ou pelo <em>tidyverse</em>) antes de prosseguir:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Ou</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="o-que-é-tidy-data" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="o-que-é-tidy-data"><span class="header-section-number">7.2</span> O que é <em>tidy data</em>?</h2>
<p>Em geral, nós passamos grande parte do tempo, reorganizando os nossos dados, para que eles fiquem no formato adequado para a nossa análise. Logo, aprender técnicas que facilitem o seu trabalho nesta atividade, pode economizar uma grande parte de seu tempo.</p>
<p>Isso é muito importante, pois uma base de dados que está bagunçada, é em geral, bagunçada em sua própria maneira. Como resultado, cada base irá exigir um conjunto de operações e técnicas diferentes das outras bases, para que ela seja arrumada. Em alguns casos, são problemas simples de serem resolvidos, já em outros, podemos ter bases que estão desarrumadas em um padrão não muito bem definido, e por isso, vão te demandar mais trabalho.</p>
<blockquote class="blockquote">
<p><em>“Tidy datasets are all alike, but every messy dataset is messy in its own way”</em>. <span class="citation" data-cites="wickham2014">WICKHAM (<a href="#ref-wickham2014" role="doc-biblioref">2014, p. 2</a>)</span>.</p>
</blockquote>
<p>Toda essa problemática, ocorre não apenas pelo erro humano, mas também porque podemos representar os nossos dados de diversas maneiras dentro de uma tabela. Cada maneira pode tanto facilitar muito o seu trabalho, quanto tornar o trabalho de outros, num inferno. Veja por exemplo, as tabelas abaixo. Ambas, apresentam os mesmos dados, mas em estruturas diferentes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>table2</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 4
  country      year type          count
  &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt;
1 Afghanistan  1999 cases           745
2 Afghanistan  1999 population 19987071
3 Afghanistan  2000 cases          2666
4 Afghanistan  2000 population 20595360
5 Brazil       1999 cases         37737
# ℹ 7 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>table3</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  country      year rate             
  &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;            
1 Afghanistan  1999 745/19987071     
2 Afghanistan  2000 2666/20595360    
3 Brazil       1999 37737/172006362  
4 Brazil       2000 80488/174504898  
5 China        1999 212258/1272915272
# ℹ 1 more row</code></pre>
</div>
</div>
<p>Antes de partirmos para a prática, vou fornecer uma base teórica que irá sustentar as suas decisões sobre como padronizar e estruturar os seus dados. Eu expliquei anteriormente, que o <code>tidyverse</code> é um conjunto de pacotes que dividem uma mesma filosofia. Isso significa, que esses pacotes possuem uma conexão forte entre si. Por exemplo, as funções desses pacotes, retornam os seus resultados em <code>tibble</code>’s, e todas as suas funções foram construídas de forma a trabalharem bem com o operador <em>pipe</em> (<code>%&gt;%</code>). Todas essas funções também foram projetadas seguindo as melhores práticas e técnicas em análise de dados. Sendo uma dessas práticas, o que é comumente chamado na comunidade de <em>tidy data</em>.</p>
<p>O conceito de <em>tidy data</em> foi definido por <span class="citation" data-cites="wickham2014">WICKHAM (<a href="#ref-wickham2014" role="doc-biblioref">2014</a>)</span>, e remete a forma como você está guardando os dados em sua tabela. Eu não estou dizendo aqui que todas as funções do <code>tidyverse</code> que apresentei até aqui, trabalham apenas com <em>tidy data</em>, mas sim, que essas funções são mais eficientes com essa estrutura <em>tidy</em>. Uma base de dados que está no formato <em>tidy</em>, compartilha das três seguintes características:</p>
<ol type="1">
<li><p>Cada variável de sua tabela, deve possuir a sua própria coluna.</p></li>
<li><p>Cada observação de sua tabela, deve possuir a sua própria linha.</p></li>
<li><p>Cada valor de sua tabela, deve possuir a sua própria célula.</p></li>
</ol>
<p>Primeiro, vou definir o que quero dizer exatamente com linhas, colunas e células de sua tabela. Em <a href="#fig-coluna-linha-tidy" class="quarto-xref">Figura&nbsp;<span>7.1</span></a> temos uma representação de uma base qualquer. O interesse nessa representação, não se trata dos valores e nomes inclusos nessa tabela, mas sim as áreas sombreadas dessa tabela, que estão lhe apresentando cada um dos componentes supracitados.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-coluna-linha-tidy" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-coluna-linha-tidy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./../Figuras/coluna_linha_celula.png" class="img-fluid figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coluna-linha-tidy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.1: Definindo colunas, linhas e células de uma tabela
</figcaption>
</figure>
</div>
</div>
</div>
<p>Agora, vamos definir o que são variáveis, observações e valores. Você já deve ter percebido, que toda base de dados, possui uma unidade básica que está sendo descrita ao longo dela. Ou seja, toda base lhe apresenta dados sobre um grupo específico (ou uma amostra) de algo. Esse “algo” pode ser um conjunto de municípios, empresas, sequências genéticas, animais, clientes, realizações de um evento estocástico, dentre outros.</p>
<p>Logo, se a minha base contém dados sobre os municípios do estado de Minas Gerais (MG), cada um desses municípios são uma observação de minha base. Ao dizer que cada observação deve possuir a sua própria linha, eu estou dizendo que todas as informações referentes a um município específico, devem estar em uma única linha. Em outras palavras, cada uma das 853 (total de municípios em MG) linhas da minha base, contém os dados de um município diferente do estado.</p>
<p>Entretanto, se a minha base descreve a evolução do PIB desses mesmos municípios nos anos de 2010 a 2020, eu não possuo mais um valor para cada município, ao longo da base. Neste momento, eu possuo 10 valores diferentes, para cada município, e mesmo que eu ainda esteja falando dos mesmos municípios, a unidade básica da minha base, se alterou. Cada um desses 10 valores, representa uma observação do PIB deste município em um ano distinto. Logo, cada um desses 10 valores para cada município, deve possuir a sua própria linha. Se o estado de Minas Gerais possui 853 municípios diferentes, isso significa que nossa base deveria ter <span class="math inline">\(10 \times 853 = 8.530\)</span> linhas. Por isso, é importante que você preste atenção em seus dados, e identifique qual é a unidade básica que está sendo tratada.</p>
<p>Agora, quando eu me referir as variáveis de sua base, eu geralmente estou me referindo as colunas de sua base, porque ambos os termos são sinônimos em análises de dados. Porém, alguns cuidados são necessários, pois as variáveis de sua base podem não se encontrar nas colunas de sua tabela. Como eu disse anteriormente, há diversas formas de representar os seus dados, e por isso, há diversas formas de alocar os componentes de seus dados ao longo de sua tabela.</p>
<p>Uma variável de sua base de dados, não é apenas um elemento que (como o próprio nome dá a entender) varia ao longo de sua base, mas também é um elemento que lhe apresenta uma característica das suas observações. Ou seja, cada variável descreve uma característica (cor de pele, população, receita, …) de cada observação (pessoa, município, empresa, …) da minha base. O que é ou não, uma característica de sua unidade básica, irá depender de qual é essa unidade básica que está sendo descrita na base.</p>
<p>A população total, é uma característica geralmente associada a regiões geográficas (municípios, países, etc.), já a cor de pele pode ser uma característica de uma amostra de pessoas entrevistadas em uma pesquisa de campo (como a PNAD contínua), enquanto o número total de empresas é uma característica associada a setores da atividade econômica (CNAE - Classificação Nacional de Atividades Econômicas).</p>
<p>Por último, os valores de sua base, correspondem aos registros das características de cada observação de sua base. Como esse talvez seja o ponto mais claro e óbvio de todos, não vou me prolongar mais sobre ele. Pois as três características de <em>tidy data</em> que citamos anteriormente são interrelacionadas, de forma que você não pode satisfazer apenas duas delas. Logo, se você está satisfazendo as duas primeiras, você não precisa se preocupar com a característica que diz respeito aos valores.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./../Figuras/tidy_data.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Três propriedades que caracterizam o formato <em>tidy data</em></figcaption>
</figure>
</div>
</div>
</div>
<p>Portanto, sempre inicie o seu trabalho, identificando a unidade básica de sua base. Em seguida, tente encontrar quais são as suas variáveis, ou as características dessa unidade básica que estão sendo descritas na base. Após isso, basta alocar cada variável em uma coluna, e reservar uma linha para cada observação diferente de sua base, que você automaticamente estará deixando uma célula para cada valor da base.</p>
<section id="será-que-você-entendeu-o-que-é-tidy-data" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="será-que-você-entendeu-o-que-é-tidy-data"><span class="header-section-number">7.2.1</span> Será que você entendeu o que é tidy data?</h3>
<p>Nessa seção vamos fazer um teste rápido, para saber se você entendeu o que é uma tabela no formato <em>tidy</em>. Olhe por algum tempo para os exemplos abaixo, e reflita sobre qual dessas tabelas está no formato <em>tidy</em>. Tente também descobrir quais são os problemas que as tabelas “não <em>tidy</em>” apresentam, ou em outras palavras, qual das três definições que apresentamos anteriormente, que essas tabelas “não <em>tidy</em>” acabam rompendo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>table1</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  country      year  cases population
  &lt;chr&gt;       &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
1 Afghanistan  1999    745   19987071
2 Afghanistan  2000   2666   20595360
3 Brazil       1999  37737  172006362
4 Brazil       2000  80488  174504898
5 China        1999 212258 1272915272
# ℹ 1 more row</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>table2</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 4
  country      year type          count
  &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt;
1 Afghanistan  1999 cases           745
2 Afghanistan  1999 population 19987071
3 Afghanistan  2000 cases          2666
4 Afghanistan  2000 population 20595360
5 Brazil       1999 cases         37737
# ℹ 7 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>table3</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  country      year rate             
  &lt;chr&gt;       &lt;dbl&gt; &lt;chr&gt;            
1 Afghanistan  1999 745/19987071     
2 Afghanistan  2000 2666/20595360    
3 Brazil       1999 37737/172006362  
4 Brazil       2000 80488/174504898  
5 China        1999 212258/1272915272
# ℹ 1 more row</code></pre>
</div>
</div>
<p>Como eu disse anteriormente, a primeira coisa que você deve fazer, é identificar a unidade básica que está sendo tratada na tabela. Nos exemplos acima, essas tabelas dizem respeito à dados de três países (Brasil, China e Afeganistão) em dois anos diferentes (1999 e 2000). Logo, a nossa tabela possui <span class="math inline">\(3 \times 2 = 6\)</span> observações diferentes. Se uma das regras, impõe que todas as linhas devem possuir informações de uma única observação, a nossa tabela deveria possuir 6 linhas. Com isso, nós já sabemos que algo está errado com a tabela 2, pois ela possui o dobro de linhas.</p>
<p>Na verdade, o problema na tabela 2 é que ela está quebrando a regra de que cada variável na tabela deve possuir a sua própria coluna. Por causa dessa regra, a tabela 2 acaba extrapolando o número de linhas necessárias. Olhe para as colunas <code>type</code> e <code>count</code>. A coluna <code>count</code> lhe apresenta os principais valores que estamos interessados nessa tabela. Porém, a coluna <code>type</code>, está lhe apresentando duas variáveis diferentes.</p>
<p>Lembre-se de que variáveis, representam características da unidade básica de sua tabela. No nosso caso, essa unidade básica se trata dos dados anuais de países, logo, <code>cases</code> e <code>population</code>, são variáveis ou características diferentes desses países. Uma dessas variáveis está lhe apresentando um dado demográfico (população total), já a outra, está lhe trazendo um indicador epidemiológico (número de casos de alguma doença). Por isso, ambas variáveis deveriam possuir a sua própria coluna.</p>
<p>Ok, mas e as tabelas 1 e 3? Qual delas é a <em>tidy</em>? Talvez, para responder essa pergunta, você deveria primeiro procurar pela tabela “não <em>tidy</em>”. Veja a tabela 3, e se pergunte: “onde se encontram os valores de população e de casos de cada país nessa tabela?”. Ao se fazer essa pergunta, você provavelmente já irá descobrir qual é o problema nessa tabela.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-table-formats" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-table-formats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./../Figuras/long_wide.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-table-formats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.2: Formas gerais que a sua tabela pode adquirir
</figcaption>
</figure>
</div>
</div>
</div>
<p>A tabela 3, também rompe com a regra de que cada variável deve possuir a sua própria coluna. Pois o número de casos e a população total, estão guardados em uma mesma coluna! Ao separar os valores de população e de número de casos na tabela 3, em duas colunas diferentes, você chega na tabela 1, que é um exemplo de tabela <em>tidy</em>, pois agora todas as três definições estão sendo respeitadas.</p>
</section>
<section id="uma-breve-definição-de-formas" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="uma-breve-definição-de-formas"><span class="header-section-number">7.2.2</span> Uma breve definição de formas</h3>
<p>Apenas para que os exemplos das próximas seções, fiquem mais claros e fáceis de se visualizar mentalmente, vou definir dois formatos gerais que a sua tabela pode assumir, que são: <em>long</em> (longa) e <em>wide</em> (larga)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Ou seja, qualquer que seja a sua tabela, ela vai em geral, estar em algum desses dois formatos, de uma forma ou de outra.</p>
<p>Esses termos (<em>long</em> e <em>wide</em>) são bem descritivos por si só. A ideia é que se uma tabela qualquer, está no formato <em>long</em>, ela adquire um aspecto visual de longa, ou em outras palavras, visualmente ela aparenta ter muitas linhas, e poucas colunas. Já uma tabela que está no formato <em>wide</em>, adquire um aspecto visual de larga, como se essa tabela possuísse mais colunas do que o necessário, e poucas linhas. Tais formas estão apresentadas em <a href="#fig-table-formats" class="quarto-xref">Figura&nbsp;<span>7.2</span></a>.</p>
</section>
</section>
<section id="operações-de-pivô" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="operações-de-pivô"><span class="header-section-number">7.3</span> Operações de pivô</h2>
<p>As operações de pivô são as principais operações que você irá utilizar para reformatar a sua tabela. Uma operação de pivô basicamente altera as dimensões de sua tabela, ou dito de outra maneira, essas operações buscam transformar colunas em linhas, ou vice-versa. Para exemplificar essas operações, vamos utilizar as tabelas que vem do próprio pacote <code>tidyr</code>. Logo, se você chamou pelo <code>tidyverse</code> através de <code>library()</code>, você tem acesso a tabela abaixo. Basta chamar no console pelo objeto <code>relig_income</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>relig_income</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 18 × 11
  religion  `&lt;$10k` `$10-20k` `$20-30k` `$30-40k` `$40-50k` `$50-75k` `$75-100k`
  &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
1 Agnostic       27        34        60        81        76       137        122
2 Atheist        12        27        37        52        35        70         73
3 Buddhist       27        21        30        34        33        58         62
4 Catholic      418       617       732       670       638      1116        949
5 Don’t kn…      15        14        15        11        10        35         21
# ℹ 13 more rows
# ℹ 3 more variables: `$100-150k` &lt;dbl&gt;, `&gt;150k` &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>Essa tabela está nos apresentando o salário médio de pessoas pertencentes a diferentes religiões. Veja que em cada coluna dessa tabela, você possui os dados de uma faixa salarial específica. Essa é uma estrutura que pode ser fácil e intuitiva em alguns momentos, mas certamente irá trazer limites importantes para você dentro do R. Devido a especialidade que o R possui sobre operações vetorizadas, o ideal seria transformarmos essa tabela para o formato <em>tidy</em>.</p>
<p>A unidade básica dessa tabela, são os grupos religiosos, e a faixa salarial representa uma característica desses grupos. Há diferentes níveis salariais na tabela, que estão sendo distribuídos ao longo de diferentes colunas. Tendo em vista isso, uma das regras não está sendo respeitada. Pois todos esses diferentes níveis salarias, representam uma única característica, ou em outras palavras, eles transmitem o mesmo tipo de informação, que é um nível salarial daquele grupo religioso. Por isso, todas essas características da tabela, deve estar em uma única coluna. A <a href="#fig-pivo-tidy" class="quarto-xref">Figura&nbsp;<span>7.3</span></a> nos apresenta, em uma representação visual, o que precisamos fazer.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-pivo-tidy" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pivo-tidy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./../Figuras/pivo1.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pivo-tidy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.3: Representação de uma operação de pivô
</figcaption>
</figure>
</div>
</div>
</div>
<p>Por isso, quando você estiver em um momento como este, em que você deseja transformar as suas linhas em colunas, ou vice-versa, você está na verdade, procurando por uma operação de pivô.</p>
<section id="adicionando-linhas-à-sua-tabela-com-pivot_longer" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="adicionando-linhas-à-sua-tabela-com-pivot_longer"><span class="header-section-number">7.3.1</span> Adicionando linhas à sua tabela com <code>pivot_longer()</code></h3>
<p>Atualmente, a tabela <code>relig_income</code> possui poucas linhas e muitas colunas, e por isso, ela adquire um aspecto visual de “larga” (ou <em>“wide”</em>). Como eu disse, seria muito interessante para você, que transformasse essa tabela, de modo a agrupar as diferentes faixas de níveis salarias em uma única coluna. Logo, se estamos falando em reduzir o número de colunas, estamos querendo alongar a base, ou dito de outra forma, aumentar o número de linhas da base. Para fazermos isso, devemos utilizar a função <code>pivot_longer()</code>.</p>
<p>Essa função possui três argumentos principais: 1) <code>cols</code>, os nomes das colunas que você deseja transformar em linhas; 2) <code>names_to</code>, o nome da nova coluna onde serão alocados os nomes, ou os rótulos das colunas que você definiu em <code>cols</code>; 3) <code>values_to</code>, o nome da nova coluna onde serão alocados os valores da sua tabela, que se encontram nas colunas que você definiu em <code>cols</code>. Como nós queremos transformar todas as colunas da tabela <code>relig_income</code>, que contém faixas salariais, eu posso simplesmente colocar no argumento <code>cols</code>, um símbolo de menos antes do nome da coluna <code>religion</code>, que é a única coluna da tabela, que não possui esse tipo de informação. Ou seja, dessa forma, eu estou dizendo à <code>pivot_longer()</code>, para transformar todas as colunas (exceto a coluna <code>religion</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>relig_income <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="sc">-</span>religion,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"income"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"values"</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 180 × 3
  religion income  values
  &lt;chr&gt;    &lt;chr&gt;    &lt;dbl&gt;
1 Agnostic &lt;$10k       27
2 Agnostic $10-20k     34
3 Agnostic $20-30k     60
4 Agnostic $30-40k     81
5 Agnostic $40-50k     76
# ℹ 175 more rows</code></pre>
</div>
</div>
<p>Vale destacar, que você pode selecionar as colunas que você deseja transformar em linhas (argumento <code>cols</code>), através dos mesmos mecanismos que utilizamos na função <code>select()</code>. Ao eliminarmos a coluna <code>religion</code> com um sinal de menos (<code>-</code>) estávamos utilizando justamente um desses métodos. Mas podemos também, por exemplo, selecionar todas as colunas, que possuem dados de tipo numérico, com a função <code>is.numeric()</code>, atingindo o mesmo resultado anterior. Ou então, poderíamos selecionar todas as colunas que possuem em seu nome, algum dígito numérico, através da expressão regular <code>"\\d"</code> (<em>digit</em>) na função <code>matches()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>relig_income <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># A linha abaixo também poderia ser: cols = matches("\\d")</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> is.numeric,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"income"</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"values"</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Portanto, sempre que utilizar a função <code>pivot_longer()</code>, duas novas colunas serão criadas. Em uma dessas colunas (<code>values_to</code>), a função irá guardar os valores que se encontravam nas colunas que você transformou em linhas. Já na outra coluna (<code>names_to</code>), a função irá criar rótulos em cada linha, que lhe informam de qual coluna (que você transformou em linhas) veio o valor disposto na coluna anterior (<code>values_to</code>). Você sempre deve definir como texto o nome dessas duas novas colunas. Isto é, sempre forneça os nomes dessas colunas, entre aspas duplas ou simples.</p>
<p>Como um outro exemplo, temos a tabela <code>billboard</code>, que também está disponível no pacote <code>tidyr</code>. Nessa tabela, temos a posição que diversas músicas ocuparam na lista da Billboard das 100 músicas mais populares no mundo, durante o ano de 2000. Portanto a posição que cada uma dessas músicas ocuparam nessa lista, ao longo do tempo, é a unidade básica que está sendo tratada nessa tabela. Agora, repare que a tabela possui muitas colunas (79 no total), onde em cada uma delas, temos a posição de uma música em uma dada semana desde a sua entrada na lista.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>billboard</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 317 × 79
  artist      track date.entered   wk1   wk2   wk3   wk4   wk5   wk6   wk7   wk8
  &lt;chr&gt;       &lt;chr&gt; &lt;date&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 2 Pac       Baby… 2000-02-26      87    82    72    77    87    94    99    NA
2 2Ge+her     The … 2000-09-02      91    87    92    NA    NA    NA    NA    NA
3 3 Doors Do… Kryp… 2000-04-08      81    70    68    67    66    57    54    53
4 3 Doors Do… Loser 2000-10-21      76    76    72    69    67    65    55    59
5 504 Boyz    Wobb… 2000-04-15      57    34    25    17    17    31    36    49
# ℹ 312 more rows
# ℹ 68 more variables: wk9 &lt;dbl&gt;, wk10 &lt;dbl&gt;, wk11 &lt;dbl&gt;, wk12 &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>São ao todo, 76 colunas contendo a posição de cada música no ranking na semana correspondente. Novamente, quando há um conjunto muito grande de colunas que desejamos selecionar, podemos utilizar os métodos alternativos de seleção que vimos em <code>select()</code>. Repare que os nomes dessas 76 colunas estão sempre no formato (<code>wk...</code>). Logo, você pode se aproveitar desse padrão, e selecionar todas essas colunas de uma vez só, usando a função <code>starts_with()</code> no argumento <code>cols</code> de <code>pivot_longer()</code>. Também podemos selecionar todas essas colunas pelos seus índices, fornecendo o vetor <code>4:79</code> para o argumento <code>cols</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>billboard_long <span class="ot">&lt;-</span> billboard <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># A linha abaixo também poderia ser: cols = 4:79</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"wk"</span>),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"week"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"position"</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>billboard_long</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24,092 × 5
  artist track                   date.entered week  position
  &lt;chr&gt;  &lt;chr&gt;                   &lt;date&gt;       &lt;chr&gt;    &lt;dbl&gt;
1 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk1         87
2 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk2         82
3 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk3         72
4 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk4         77
5 2 Pac  Baby Don't Cry (Keep... 2000-02-26   wk5         87
# ℹ 24,087 more rows</code></pre>
</div>
</div>
</section>
<section id="adicionando-colunas-à-sua-tabela-com-pivot_wider" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="adicionando-colunas-à-sua-tabela-com-pivot_wider"><span class="header-section-number">7.3.2</span> Adicionando colunas à sua tabela com <code>pivot_wider()</code></h3>
<p>Por outro lado, você talvez deseje realizar a operação contrária. Ou seja, se você deseja transformar linhas de sua tabela, em novas colunas, você deve utilizar a função <code>pivot_wider()</code>, que possui argumentos muito parecidos com os de <code>pivot_longer()</code>.</p>
<p>Vamos começar com um exemplo simples. Veja a tabela <code>df</code> que estou criando logo abaixo. Nessa tabela, temos dados como o peso, a idade e a altura de cinco pessoas diferentes. Porém, perceba que essa tabela, não está no formato <em>tidy</em>. Pois temos três informações (peso, idade e altura) que representam características diferentes da unidade básica da tabela (pessoas), condensadas em uma mesma coluna (<code>variavel</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">nome =</span> <span class="fu">c</span>(<span class="st">"Ana"</span>, <span class="st">"Ana"</span>, <span class="st">"Ana"</span>, <span class="st">"Eduardo"</span>, <span class="st">"Eduardo"</span>, </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="st">"Eduardo"</span>, <span class="st">"Paulo"</span>, <span class="st">"Paulo"</span>, <span class="st">"Paulo"</span>, <span class="st">"Henrique"</span>, <span class="st">"Henrique"</span>, </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="st">"Henrique"</span>, <span class="st">"Letícia"</span>, <span class="st">"Letícia"</span>, <span class="st">"Letícia"</span>), <span class="at">variavel =</span> <span class="fu">c</span>(<span class="st">"idade"</span>, </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="st">"peso"</span>, <span class="st">"altura"</span>, <span class="st">"idade"</span>, <span class="st">"peso"</span>, <span class="st">"altura"</span>, <span class="st">"idade"</span>, <span class="st">"peso"</span>, </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="st">"altura"</span>, <span class="st">"idade"</span>, <span class="st">"peso"</span>, <span class="st">"altura"</span>, <span class="st">"idade"</span>, <span class="st">"peso"</span>, <span class="st">"altura"</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>), <span class="at">valor =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">61</span>, <span class="fl">1.67</span>, <span class="dv">18</span>, <span class="dv">90</span>, <span class="fl">1.89</span>, <span class="dv">19</span>, <span class="dv">68</span>, <span class="fl">1.67</span>, <span class="dv">23</span>, <span class="dv">82</span>, </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fl">1.72</span>, <span class="dv">27</span>, <span class="dv">56</span>, <span class="fl">1.58</span>))</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 3
  nome    variavel valor
  &lt;chr&gt;   &lt;chr&gt;    &lt;dbl&gt;
1 Ana     idade    20   
2 Ana     peso     61   
3 Ana     altura    1.67
4 Eduardo idade    18   
5 Eduardo peso     90   
# ℹ 10 more rows</code></pre>
</div>
</div>
<p>Portanto, tendo identificado o problema, precisamos agora, separar as três variáveis contidas na coluna <code>variavel</code>, em três novas colunas da tabela <code>df</code>. Logo, precisamos alargar a nossa base, pois estamos eliminando linhas e adicionando colunas à tabela.</p>
<p>Já sabemos que podemos utilizar a função <code>pivot_wider()</code> para esse trabalho, e os seus argumentos são: 1) <code>id_cols</code>, que são as colunas suficientes para (ou capazes de) identificar uma única observação de sua base; 2) <code>names_from</code>, que é a coluna de sua tabela que contém as linhas a serem dividas, ou transformadas, em várias outras colunas; 3) <code>values_from</code>, que é a coluna com os valores a serem posicionados nas novas células, que serão criadas durante o processo de “alargamento” da sua tabela.</p>
<p>Antes de prosseguirmos para os exemplos práticos, é provavelmente uma boa ideia, refletirmos sobre o que o argumento <code>id_cols</code> significa. As colunas a serem estipuladas no argumento <code>id_cols</code> são aquelas que conseguem identificar cada observação de sua base. No nosso caso, a tabela <code>df</code>, contém dados sobre características físicas ou biológicas, de cinco pessoas diferentes. Logo, a unidade básica dessa tabela, são as pessoas que estão sendo descritas nela, e por isso, a coluna <code>nome</code> é capaz de identificar cada observação (unidade básica) da tabela, pois ela nos traz justamente um código social de identificação, isto é, o nome dessas pessoas.</p>
<p>Pensando em um outro exemplo, se você dispõe de uma base que descreve o PIB de cada município do estado de Minas Gerais, você precisa definir em <code>id_cols</code>, a coluna (ou o conjunto de colunas) que é capaz de identificar cada um dos 853 municípios de MG, pois esses municípios são a unidade básica da tabela. Porém, se a sua base está descrevendo o PIB desses mesmos municípios, mas agora ao longo dos anos de 2010 a 2020, a sua unidade básica passa a ter um componente temporal, e se torna a evolução desses municípios ao longo do tempo. Dessa forma, você precisaria não apenas de uma coluna que seja capaz de identificar qual o município que está sendo descrito na base, mas também de uma outra coluna que possa identificar qual o ano que a informação desse município se refere.</p>
<p>Tendo isso em mente, vamos partir para os próximos dois argumentos. No nosso caso, queremos pegar as três variáveis que estão ao longo da coluna <code>variavel</code>, e separá-las em três colunas diferentes. Isso é exatamente o que devemos definir em <code>names_from</code>. O que este argumento está pedindo, é o nome da coluna que contém os valores que vão servir de nome para as novas colunas que <code>pivot_wider()</code> irá criar. Ou seja, ao fornecermos a coluna <code>variavel</code> para <code>names_from</code>, <code>pivot_wider()</code> irá criar uma nova coluna para cada valor único que se encontra na coluna <code>variavel</code>. Como ao longo da coluna <code>variavel</code>, temos três valores diferentes (peso, altura e idade), <code>pivot_wider()</code> irá criar três novas colunas que possuem os nomes de <code>peso</code>, <code>altura</code> e <code>idade</code>.</p>
<p>Ao criar as novas colunas, você precisa preenchê-las de alguma forma, a menos que você deseja deixá-las vazias. Em outras palavras, a função <code>pivot_wider()</code> irá lhe perguntar: “Ok, eu criei as colunas que você me pediu para criar, mas eu devo preenchê-las com que valores?”. Você deve responder essa pergunta, através do argumento <code>values_from</code>, onde você irá definir qual é a coluna que contém os valores que você deseja alocar ao longo dessas novas colunas (que foram criadas de acordo com os valores contidos na coluna que você definiu em <code>names_from</code>). Na nossa tabela <code>df</code>, é a coluna <code>valor</code> que contém os registros, ou os valores que cada variável (idade, altura e peso) assume nessa amostra. Logo, é essa coluna que devemos conectar à <code>values_from</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">id_cols =</span> nome,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> variavel,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> valor</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  nome     idade  peso altura
  &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1 Ana         20    61   1.67
2 Eduardo     18    90   1.89
3 Paulo       19    68   1.67
4 Henrique    23    82   1.72
5 Letícia     27    56   1.58</code></pre>
</div>
</div>
<p>Esse foi um exemplo simples de como utilizar a função, e que vai lhe servir de base para praticamente qualquer aplicação de <code>pivot_wider()</code>. Porém, em algumas situações que você utilizar <code>pivot_wider()</code>, pode ser que a sua tabela não possua colunas o suficiente, que possam identificar unicamente cada observação de sua base, e isso, ficará mais claro com um outro exemplo.</p>
<p>Com o código abaixo, você é capaz de recriar a tabela <code>vendas</code>, em seu R. Lembre-se de executar a função <code>set.seed()</code> antes de criar a tabela <code>vendas</code>, pois é essa função que garante que você irá recriar exatamente a mesma tabela que a minha. Nessa tabela <code>vendas</code>, possuímos vendas hipóteticas de diversos produtos (identificados por <code>produtoid</code>), realizadas por alguns vendedores (identificados por <code>usuario</code>) que arrecadaram em cada venda os valores descritos na coluna <code>valor</code>. Perceba também, que essas vendas são diárias, pois possuímos outras três colunas (<code>ano</code>, <code>mes</code> e <code>dia</code>) que definem o dia em que a venda ocorreu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>nomes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Ana"</span>, <span class="st">"Eduardo"</span>, <span class="st">"Paulo"</span>, <span class="st">"Henrique"</span>, <span class="st">"Letícia"</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>produto <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"10032"</span>, <span class="st">"10013"</span>, <span class="st">"10104"</span>, <span class="st">"10555"</span>, <span class="st">"10901"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>vendas <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">ano =</span> <span class="fu">sample</span>(<span class="dv">2010</span><span class="sc">:</span><span class="dv">2020</span>, <span class="at">size =</span> <span class="dv">10000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mes =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">size =</span> <span class="dv">10000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">dia =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">31</span>, <span class="at">size =</span> <span class="dv">10000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">usuario =</span> <span class="fu">sample</span>(nomes, <span class="at">size =</span> <span class="dv">10000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">valor =</span> <span class="fu">rnorm</span>(<span class="dv">10000</span>, <span class="at">mean =</span> <span class="dv">5000</span>, <span class="at">sd =</span> <span class="dv">1600</span>),</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">produtoid =</span> <span class="fu">sample</span>(produto, <span class="at">size =</span> <span class="dv">10000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(ano, mes, dia, usuario)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Perceba pelos resultados abaixo, que nós temos cinco vendedores e cinco produtos diferentes que estão sendo descritos ao longo da tabela <code>vendas</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(vendas<span class="sc">$</span>usuario)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Ana"      "Henrique" "Letícia"  "Eduardo"  "Paulo"   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(vendas<span class="sc">$</span>produtoid)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "10104" "10013" "10555" "10032" "10901"</code></pre>
</div>
</div>
<p>Se você tentar distribuir tanto os vendedores (<code>usuario</code>), quanto os produtos vendidos (<code>produtoid</code>), em novas colunas dessa tabela, utilizando <code>pivot_wider()</code>, um aviso será levantado, e o resultado dessa operação (apesar de correto) será provavelmente, muito estranho para você:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>vendas_wide <span class="ot">&lt;-</span> vendas <span class="sc">%&gt;%</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">id_cols =</span> <span class="fu">c</span>(<span class="st">"ano"</span>, <span class="st">"mes"</span>, <span class="st">"dia"</span>, <span class="st">"produtoid"</span>),</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> usuario,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> valor</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Values from `valor` are not uniquely identified; output will contain list-cols.
• Use `values_fn = list` to suppress this warning.
• Use `values_fn = {summary_fun}` to summarise duplicates.
• Use the following dplyr code to identify duplicates.
  {data} |&gt;
  dplyr::summarise(n = dplyr::n(), .by = c(ano, mes, dia, produtoid, usuario))
  |&gt;
  dplyr::filter(n &gt; 1L)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>vendas_wide</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,845 × 9
    ano   mes   dia produtoid Ana       Henrique  Letícia   Eduardo   Paulo 
  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;     &lt;list&gt;    &lt;list&gt;    &lt;list&gt;    &lt;list&gt;    &lt;list&gt;
1  2010     1     1 10104     &lt;dbl [1]&gt; &lt;dbl [1]&gt; &lt;NULL&gt;    &lt;NULL&gt;    &lt;NULL&gt;
2  2010     1     2 10013     &lt;NULL&gt;    &lt;dbl [1]&gt; &lt;NULL&gt;    &lt;NULL&gt;    &lt;NULL&gt;
3  2010     1     3 10555     &lt;dbl [1]&gt; &lt;NULL&gt;    &lt;dbl [1]&gt; &lt;NULL&gt;    &lt;NULL&gt;
4  2010     1     4 10555     &lt;dbl [1]&gt; &lt;NULL&gt;    &lt;NULL&gt;    &lt;NULL&gt;    &lt;NULL&gt;
5  2010     1     4 10013     &lt;NULL&gt;    &lt;NULL&gt;    &lt;NULL&gt;    &lt;dbl [1]&gt; &lt;NULL&gt;
# ℹ 7,840 more rows</code></pre>
</div>
</div>
<p>Como podemos ver pelo resultado acima, uma mensagem de aviso apareceu, nos informando que os valores não podem ser unicamente identificados através das colunas que fornecemos em <code>id_cols</code> (<em>Values are not uniquely identified</em>), e que por isso, a função <code>pivot_wider()</code>, acabou transformando as novas colunas que criamos, em listas (<em>output will contain list-cols.</em>).</p>
<p>Ou seja, cada uma das colunas que acabamos de criar com <code>pivot_wider()</code>, são listas (e.g.&nbsp;<code>list</code>). Isso pode ser estranho para muitos usuários, pois na maioria das vezes, as colunas de suas tabelas serão vetores atômicos<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Um outro motivo que provavelmente levantou bastante dúvida em sua cabeça é: “Como assim as colunas que forneci não são capazes de identificar unicamente os valores? Em que sentido elas não são capazes de realizar tal ação?”.</p>
<p>A resposta curta simples é que, existem alguns casos dentro da tabela <code>vendas</code> em que, um mesmo vendedor conseguiu vender o mesmo produto, em uma mesma data, mais de uma única vez. Por causa disso, a combinação de colunas <code>ano, mes, dia</code> e <code>produtoid</code> se torna insuficiente para diferenciar uma venda da outra. Por exemplo, observe abaixo, que os vendedores Ana e Henrique venderam no dia 01/01/2010, uma unidade do produto de ID 10104:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>vendas <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>    produtoid <span class="sc">==</span> <span class="dv">10104</span>,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    ano <span class="sc">==</span> <span class="dv">2010</span>, mes <span class="sc">==</span> <span class="dv">1</span>, dia <span class="sc">==</span> <span class="dv">1</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
    ano   mes   dia usuario  valor produtoid
  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt;    
1  2010     1     1 Ana      3907. 10104    
2  2010     1     1 Henrique 6139. 10104    </code></pre>
</div>
</div>
<p>Neste ponto, se pergunte: “Ok, Ana vendeu uma unidade do produto 10104, no dia 01. Mas e se ela tivesse vendido duas unidades desse mesmo produto 10104, no dia 01?”. Tente imaginar para onde os valores dessas vendas seriam movidos após a operação de pivô que realizamos no exemplo anterior. Isso não é uma questão trivial. Pois temos agora dados de duas vendas diferentes…mas apenas uma célula disponível em nossa tabela, para guardar esses dados. É a partir deste choque, que podemos identificar qual foi o motivo para o uso de listas nas novas colunas.</p>
<p>Ou seja, temos uma única célula na tabela (localizada na primeira linha, e quinta coluna da tabela), que deve conter o valor arrecadado na venda do produto 10104, realizada pela vendedora Ana no dia 01/01/2010. Você poderia pensar: “Bem, por que não somar os valores dessas duas vendas? Dessa forma, temos apenas um valor para encaixar nessa célula”. Essa é uma alternativa possível, porém, ela gera perda de informação, especialmente se o valor arrecadado nas duas operações forem diferentes. Por exemplo, se a receita da primeira venda foi de 3907, e da segunda, de 4530. Com essa alternativa, nós sabemos que a soma das duas vendas ocorridas naquele dia, geraram 8437 reais de receita, mas nós não sabemos mais qual das duas vendas teve o maior valor de venda.</p>
<p>Isso é particularmente importante, pois podemos gerar o mesmo valor (8437 reais) de múltiplas formas. Pode ser que a Ana tenha vendido cinco unidades do produto 10104, tendo arrecadado em cada venda, o valor de 1687,4 reais. Mas ela poderia atingir o mesmo valor, ao vender dez unidades do produto 10104, dessa vez, arrecadando um valor médio bem menor, de 843,7 reais. Portanto, se utilizarmos a soma desses valores, como forma de contornarmos o problema posto anteriormente, os administradores da loja não poderão mais inferir da tabela <code>vendas</code>, se as suas vendas tem se reduzido em quantidade, ou se o valor arrecadado em cada venda, tem caído ao longo dos últimos anos.</p>
<p>Apesar de ser uma alternativa ruim em muitos casos, ela pode fazer sentido para o seu caso específico. Nesta situação, as versões mais recentes do pacote <code>tidyr</code>, oferecem na função <code>pivot_wider()</code> o argumento <code>values_fn</code>, onde você pode fornecer o nome de uma função a ser aplicada sobre os valores dispostos em cada célula. Logo, se quiséssemos somar os valores de vendas de cada célula criada na tabela <code>vendas_wide</code>, poderíamos realizar os comandos abaixo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>vendas <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">id_cols =</span> <span class="fu">c</span>(<span class="st">"ano"</span>, <span class="st">"mes"</span>, <span class="st">"dia"</span>, <span class="st">"produtoid"</span>),</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> usuario,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> valor,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_fn =</span> sum</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,845 × 9
    ano   mes   dia produtoid   Ana Henrique Letícia Eduardo Paulo
  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;     &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
1  2010     1     1 10104     3907.    6139.     NA      NA     NA
2  2010     1     2 10013       NA     5510.     NA      NA     NA
3  2010     1     3 10555     5296.      NA    3525.     NA     NA
4  2010     1     4 10555     5102.      NA      NA      NA     NA
5  2010     1     4 10013       NA       NA      NA    6051.    NA
# ℹ 7,840 more rows</code></pre>
</div>
</div>
<p>Portanto, a função <code>pivot_wide()</code> foi obrigada a transformar as novas colunas criadas em colunas de lista (i.e.&nbsp;<code>list-cols</code>) pelo simples fato de que a função encontrou casos em que um mesmo vendedor vendeu o mesmo produto mais de uma vez na mesma data, e que por isso, o conjunto de colunas fornecidos no argumento <code>id_cols</code> se tornou insuficiente para identificar uma única observação da base.</p>
<p>Você talvez pense: “Por que não fornecemos então todas as colunas da tabela para <code>id_cols</code>?”. Primeiro, esse questionamento carrega um pressuposto que não necessariamente se confirma, que é o de que os valores das vendas realizadas por um mesmo vendedor, de um mesmo produto, e no mesmo dia, são diferentes em todas as ocasiões. Algo que é possível, mas não necessariamente ocorre ao longo de toda a base. O segundo problema, é que a coluna <code>valor</code> não está mais disponível para ser utilizada por <code>id_cols</code>, pois se você se lembrar, nós conectamos essa coluna a <code>values_from</code>. Isso significa, que essa coluna já está sendo utilizada para preencher as novas células que estão sendo criadas por <code>pivot_wider()</code>, e, portanto, ela não pode ocupar dois espaços ao mesmo tempo. Tanto que se você tentar adicionar a coluna <code>valor</code> a <code>id_cols</code>, você irá perceber que nada se altera, e o mesmo resultado é gerado.</p>
<p>Portanto, não há uma resposta fácil para uma situação como essa, onde mesmo fornecendo todas as colunas para <code>id_cols</code> em <code>pivot_wider()</code>, a função ainda não é capaz de identificar unicamente cada valor da coluna que você forneceu em <code>value_from</code>. Você pode utilizar uma solução que gera perda de informação, ao aplicar uma função sumária, ou seja, uma função para agregar esses valores de forma que eles se tornem únicos, dados os conjuntos de colunas que você forneceu em <code>id_cols</code>. Uma outra possibilidade, é que você esteja utilizando a operação de pivô errada. Ou seja, a melhor alternativa seria alongar (<code>pivot_longer()</code>) a sua base, ao invés de alargá-la.</p>
<p>Agora, uma última possibilidade mais promissora, é que você esteja realizando a operação correta, e que faz sentido lógico manter essas colunas como listas de acordo com o que você deseja realizar com a base. Isso inclui o uso de um ferramental que está um pouco além desse capítulo. Por outro lado, lidar com <em>nested data</em>, é mais uma questão de experiência, de se acostumar com tal estrutura, e saber as funções adequadas, do que aprender algo muito diferente do que mostramos aqui. Um outro conhecimento que é de extrema importância nessas situações, é conhecer muito bem como as listas funcionam no R. Se você conhecer bem essa estrutura, você não terá dificuldades em navegar por <em>nested data</em>. Para uma visão melhor do potencial que <em>nested data</em> pode trazer para sua análise, eu recomendo que você procure por uma excelente palestra de Hadley Wickham, entitulada <em>“Managing many models with R”</em><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
</section>
</section>
<section id="trabalhando-com-dados-aninhados-ou-em-árvores-json-html-xml" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="trabalhando-com-dados-aninhados-ou-em-árvores-json-html-xml"><span class="header-section-number">7.4</span> Trabalhando com dados aninhados ou em árvores (JSON, HTML, XML)</h2>
<p>Uma área em que o <code>tidyr</code> se desenvolveu muito nos últimos anos é a área de dados aninhados. Essa área envolve todo tipo de dado e estrutura que possui altos níveis de aninhamento (ou <em>nesting</em>). Ou seja, são estruturas que contém outras estruturas, que por sua vez contém um outro grupo de estruturas dentro delas, e assim por diante, seguindo um nível de profundidade grande.</p>
<p>Esses dados são tipicamente encontrados no mundo real em formatos que representam árvores (ou <em>trees</em>) de informação. Grandes exemplos são dados em JSON, em HTML, ou em XML. Esses formatos são massivamente utilizados dentro da Web, isto é, em sistemas e plataformas que são acessadas pela internet, como APIs, plataformas de streaming, redes sociais, e outros tipos de <em>Web Application</em>’s. Como a internet e a Web são parte fundamental hoje da vida humana como um todo, um volume monumental de dados em JSON, HTML, etc. é produzido a todo momento. Por isso, analisar esse tipo de dado em formato de árvores tem sido cada vez mais comum e necessário dentro do mundo da estatística e da análise de dados.</p>
<p>Quando trazidos para dentro do R, esses tipos de dados (JSON, HTML, etc.) são tipicamente representados através de listas (i.e.&nbsp;<code>list</code>), e geralmente, essas listas contém múltiplos níveis de aninhamento (i.e.&nbsp;listas que contém listas, que contém mais listas, etc.). Dentro do <code>tidyr</code>, o trabalho com esse tipo de dado é tipicamente associado com o termo <em>rectangling</em> (que seria algo próximo do verbo “enquadrar”). A ideia é utilizarmos o <code>tidyr</code> para encaixar (ou “enquadrar”) esse tipo de dado aninhado de modo eficiente dentro de um <code>data.frame</code>. Hoje, o <code>tidyr</code> tem três funções principais para fazer esse trabalho, que são <code>unnest_longer()</code>, <code>unnest_wider()</code>, e <code>hoist()</code>.</p>
<p>Como exemplos nessa seção, vamos usar os dados fornecidos pelo pacote <code>repurrrsive</code>, que contém alguns exemplos de dados aninhados perfeitos para as demonstrações feitas aqui. Lembre-se de instalar esse pacote usando <code>install.packages()</code>, e, em seguida, carregar ele para sua sessão com <code>library()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(repurrrsive)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="criando-colunas-a-partir-dos-atributos-da-lista" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="criando-colunas-a-partir-dos-atributos-da-lista"><span class="header-section-number">7.4.1</span> Criando colunas a partir dos atributos da lista</h3>
<p>A função <code>unnest_wider()</code> busca transformar os atributos encontrados em cada elemento de uma lista, em novas colunas de seu <code>data.frame/tibble</code>. Como exemplo, vamos analisar os dados no objeto <code>gh_users</code>. Se você conseguiu carregar o pacote <code>repurrrsive</code> com sucesso para a sua sessão, você tem acesso a este objeto.</p>
<p>Em resumo, <code>gh_users</code> é uma lista contendo dados sobre seis usuários diferentes do GitHub. Cada elemento dessa lista contém uma outra lista com os atributos/características que descrevem um usuário específico. Portanto, temos uma “lista de seis listas”. Em cada elemento dessa lista, temos uma nova lista contendo vários atributos diferentes, como <code>username</code> desse usuário, a sua cidade (<code>location</code>), o seu <code>email</code>, a empresa onde trabalha (<code>company</code>). Enfim, temos várias informações diferentes de cada usuário.</p>
<p>Primeiro, vamos armazenar essa lista dentro de um <code>tibble</code>. Perceba que, por ser uma lista, o <code>tibble</code> resultante cria uma coluna do tipo <code>list</code> para armazenar esse objeto. Perceba também pela notação <code>list[30]</code> presente nas linhas dessa coluna, que cada uma das seis listas que estão dentro dessa lista inicial, possuem em torno de 30 atributos diferentes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>users <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">user =</span> gh_users)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>users</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1
  user             
  &lt;list&gt;           
1 &lt;named list [30]&gt;
2 &lt;named list [30]&gt;
3 &lt;named list [30]&gt;
4 &lt;named list [30]&gt;
5 &lt;named list [30]&gt;
# ℹ 1 more row</code></pre>
</div>
</div>
<p>Em resumo, a função <code>unnest_wider()</code> vai “expandir” os atributos dessa lista em novas colunas de nossa tabela. Em outras palavras, os atributos presentes em cada “sublista” (ou em cada elemento) da lista inicial vai virar uma nova coluna dentro da nossa tabela. Como vimos acima que cada “sublista” da lista parece ter em torno de 30 atributos diferentes, significa que a função <code>unnest_wider()</code> vai criar em torno de 30 colunas novas.</p>
<p>Para usarmos essa função, basta fornecermos o <code>tibble</code> com os nossos dados em seu primeiro argumento, e, em seguida, escrevemos no segundo argumento, o nome da coluna dentro desse <code>tibble</code> que contém a lista que queremos “expandir” em novas colunas. Como armazenamos o objeto <code>gh_users</code> em uma coluna chamada <code>user</code> em nossa tabela, eu escrevo o nome dessa coluna no segundo argumento da função.</p>
<p>Como esperado, um novo <code>tibble</code> foi criado, contendo 30 colunas e 6 linhas. Cada linha nessa tabela representa um dos elementos da lista <code>gh_users</code>, e cada coluna nessa tabela, contém os dados de um atributo que estava armazenado dentro de cada “sublista”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>users_wide <span class="ot">&lt;-</span> users <span class="sc">|&gt;</span> <span class="fu">unnest_wider</span>(user)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>users_wide</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 30
  login     id avatar_url gravatar_id url   html_url followers_url following_url
  &lt;chr&gt;  &lt;int&gt; &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;         &lt;chr&gt;        
1 gabo… 6.60e5 https://a… ""          http… https:/… https://api.… https://api.…
2 jenn… 5.99e5 https://a… ""          http… https:/… https://api.… https://api.…
3 jtle… 1.57e6 https://a… ""          http… https:/… https://api.… https://api.…
4 juli… 1.25e7 https://a… ""          http… https:/… https://api.… https://api.…
5 leep… 3.51e6 https://a… ""          http… https:/… https://api.… https://api.…
# ℹ 1 more row
# ℹ 22 more variables: gists_url &lt;chr&gt;, starred_url &lt;chr&gt;, …</code></pre>
</div>
</div>
</section>
<section id="criando-linhas-a-partir-dos-atributos-da-lista" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="criando-linhas-a-partir-dos-atributos-da-lista"><span class="header-section-number">7.4.2</span> Criando linhas a partir dos atributos da lista</h3>
<p>Enquanto a função <code>unnest_wider()</code> cria uma nova coluna para cada atributo encontrado dentro de cada elemento da lista, a função <code>unnest_longer()</code> faz o processo inverso. Isto é, ela cria uma nova linha para cada atributo encontrado em cada elemento da lista.</p>
<p>Apesar dessa diferença, <code>unnest_longer()</code> tem os mesmos argumentos que o seu par, <code>unnest_wider()</code>. Ou seja, no primeiro argumento da função, você fornece o <code>tibble</code> que contém os seus dados, e, em seguida, no segundo argumento, você fornece o nome da coluna dentro desse <code>tibble</code> que contém a lista que você gostaria de “expandir” em novas linhas de sua tabela. Se aplicarmos <code>unnest_longer()</code> sobre a tabela <code>users</code>, teremos como resultado, uma nova tabela contendo <span class="math inline">\(6 \times 30 = 180\)</span> linhas. Cada linha conteria o dado de um único atributo de um indivíduo específico.</p>
<p>Porém, o objeto <code>gh_users</code> é um mal exemplo de uso da <code>unnest_longer()</code>. Um exemplo melhor de uso para essa função é o objeto <code>gh_repos</code> que também é uma lista com vários níveis de aninhamento. No primeiro nível, essa lista contém 6 elementos. Cada elemento corresponde a uma nova lista. Ou seja, temos 6 “sublistas”. Cada “sublista” contém os dados de um usuário específico. Dentro de cada uma dessas 6 “sublistas”, temos novamente, mais um nível de “sublistas”. Cada sublista presente nesse terceiro nível contém dados e atributos que descrevem um repositório Git que o usuário correspondente possui dentro da plataforma do GitHub.</p>
<p>Ou seja, no fim das contas, o objeto <code>gh_repos</code> é uma lista de repositórios que cada usuário possui dentro da plataforma GitHub, e está num nível de aninhamento em 3 níveis de profundidade, i.e.&nbsp;uma lista que contém listas de usuários, que por sua vez, contém listas de repositórios (<code>list -&gt; list -&gt; list</code>). No exemplo abaixo, podemos ver alguns dos atributos que estão disponíveis sobre o primeiro repositório pertencente ao primeiro usuário descrito nessa lista. Temos ao todo 68 atributos diferentes sobre o repositório, porém, no código abaixo usei a função <code>head()</code> para mostrar apenas uma parte desses 68 atributos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>gh_repos[[<span class="dv">1</span>]][[<span class="dv">1</span>]] <span class="sc">|&gt;</span> <span class="fu">names</span>() <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "id"        "name"      "full_name" "owner"     "private"   "html_url" </code></pre>
</div>
</div>
<p>Novamente, eu posso armazenar essa lista dentro de um <code>tibble</code>, e começar a aplicar as nossas funções de <code>unnest_*()</code> para “desembaraçar” essas listas em um formato mais amigável. Veja abaixo que ao aplicarmos a função <code>unnest_longer()</code> sobre essa lista, temos como resultado um novo <code>tibble</code> com 176 linhas. Cada linha agora contém os dados de um repositório diferente. Isso significa que, dentro da lista <code>gh_repos</code> temos no total 176 repositórios descritos ao longo dos 6 usuários. Logo, cada usuário tem aproximadamente 30 repositórios dentro da plataforma.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>repos <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">repo =</span> gh_repos)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>repos_longer <span class="ot">&lt;-</span> repos <span class="sc">|&gt;</span> <span class="fu">unnest_longer</span>(repo)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>repos_longer</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 176 × 1
  repo             
  &lt;list&gt;           
1 &lt;named list [68]&gt;
2 &lt;named list [68]&gt;
3 &lt;named list [68]&gt;
4 &lt;named list [68]&gt;
5 &lt;named list [68]&gt;
# ℹ 171 more rows</code></pre>
</div>
</div>
<p>Agora que temos esses dados nesse formato, podemos aplicar uma segunda transformação, com a função <code>unnest_wider()</code>, para transformar os atributos de cada repositório em novas colunas da tabela. Com isso, temos uma nova tabela com 68 colunas e 176 linhas, em um formato que é ideal para o R, e que é amigável para o nosso cérebro.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>repos_wider <span class="ot">&lt;-</span> repos_longer <span class="sc">|&gt;</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest_wider</span>(repo)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>repos_wider</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 176 × 68
        id name  full_name owner        private html_url description fork  url  
     &lt;int&gt; &lt;chr&gt; &lt;chr&gt;     &lt;list&gt;       &lt;lgl&gt;   &lt;chr&gt;    &lt;chr&gt;       &lt;lgl&gt; &lt;chr&gt;
1 61160198 after gaborcsa… &lt;named list&gt; FALSE   https:/… Run Code i… FALSE http…
2 40500181 argu… gaborcsa… &lt;named list&gt; FALSE   https:/… Declarativ… FALSE http…
3 36442442 ask   gaborcsa… &lt;named list&gt; FALSE   https:/… Friendly C… FALSE http…
4 34924886 base… gaborcsa… &lt;named list&gt; FALSE   https:/… Do we get … FALSE http…
5 61620661 cite… gaborcsa… &lt;named list&gt; FALSE   https:/… Test R pac… TRUE  http…
# ℹ 171 more rows
# ℹ 59 more variables: forks_url &lt;chr&gt;, keys_url &lt;chr&gt;, …</code></pre>
</div>
</div>
<p>De forma análoga, você poderia encadear (ou conectar) as transformações executadas por essas duas funções, através do operador <em>pipe</em> (<code>%&gt;%</code> ou <code>|&gt;</code>). Desse modo, você eliminaria os objetos intermediários.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Produz o mesmo resultado que o exemplo anterior:</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>repos <span class="sc">|&gt;</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest_longer</span>(repo) <span class="sc">|&gt;</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest_wider</span>(repo)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="coletando-atributos-específicos-de-sua-lista" class="level3" data-number="7.4.3">
<h3 data-number="7.4.3" class="anchored" data-anchor-id="coletando-atributos-específicos-de-sua-lista"><span class="header-section-number">7.4.3</span> Coletando atributos específicos de sua lista</h3>
<p>A função <code>hoist()</code> é quase idêntica à função <code>unnest_wider()</code>. Ou seja, essa função te permite acessar atributos de sua lista, e transformar esses atributos em novas colunas de sua tabela. Contudo, a função <code>unnest_wider()</code> vai, por padrão, transformar <strong>todos</strong> os atributos que ela encontrar pela frente em novas colunas. Por outro lado, a função <code>hoist()</code> é mais seletiva, pois ela te permite selecionar especificamente quais atributos você deseja coletar de sua lista e transformar em novas colunas.</p>
<p>Então, você usa a função <code>unnest_wider()</code> quando você quer transformar em uma tacada só, todos os atributos de sua lista em colunas. Enquanto a função <code>hoist()</code> é mais apropriada para aqueles momentos em que você quer extrair apenas um conjunto pequeno de atributos de sua lista. No primeiro argumento da função <code>hoist()</code>, você deve fornecer como input, o <code>tibble</code> que contém todos os seus dados. Já no segundo argumento, você deve fornecer o nome da coluna que contém a lista que você deseja transformar. Em seguida, você deve fornecer uma sequência de <em>key-value pairs</em> na estrutura <code>&lt;nome-nova-coluna&gt; = &lt;nome-atributo-selecionado&gt;</code>. Cada par descreve um atributo específico que você deseja extrair da lista.</p>
<p>No exemplo abaixo, eu estou usando novamente a tabela <code>repos_longer</code> que criamos na sessão anterior. Porém, ao invés de usar a função <code>unnest_wider()</code> e extrair todos os atributos de uma vez só, vamos extrair só alguns atributos de cada repositório. Perceba nesse exemplo, que seleciono apenas 5 atributos (<code>id</code>, <code>name</code>, <code>full_name</code>, <code>private</code> e <code>url</code>) da lista, e como resultado, temos uma tabela de apenas 6 colunas, ao invés das 68 colunas produzidas por <code>unnest_wider()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>repos_longer <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hoist</span>(</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>    repo,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">id =</span> <span class="st">"id"</span>,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"name"</span>,</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">full_name =</span> <span class="st">"full_name"</span>,</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">private =</span> <span class="st">"private"</span>,</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">url =</span> <span class="st">"url"</span></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 176 × 6
        id name        full_name               private url          repo        
     &lt;int&gt; &lt;chr&gt;       &lt;chr&gt;                   &lt;lgl&gt;   &lt;chr&gt;        &lt;list&gt;      
1 61160198 after       gaborcsardi/after       FALSE   https://api… &lt;named list&gt;
2 40500181 argufy      gaborcsardi/argufy      FALSE   https://api… &lt;named list&gt;
3 36442442 ask         gaborcsardi/ask         FALSE   https://api… &lt;named list&gt;
4 34924886 baseimports gaborcsardi/baseimports FALSE   https://api… &lt;named list&gt;
5 61620661 citest      gaborcsardi/citest      FALSE   https://api… &lt;named list&gt;
# ℹ 171 more rows</code></pre>
</div>
</div>
<p>Além disso, a função <code>hoist()</code> te permite facilmente acessar múltiplos níveis de sua lista, através de uma sintaxe que se assemelha ao XPath em arquivos XML, ou ao JSON Path em arquivos JSON, onde você consegue “encadear” em sequência vários indíces, e com isso, facilmente acessar um atributo que está bem no fundo de sua lista. No exemplo acima, eu forneci os nomes dos atributos a serem extraídos, como simples <em>strings</em> (exemplo: <code>"name"</code> ou <code>"private"</code>). Mas para utilizar essa sintaxe especial disponível em <code>hoist()</code>, tudo que você precisa fazer é fornecer uma lista como input.</p>
<p>Dentro dessa lista de input, você pode definir uma sequência de índices, que vão ser conectados em sequência para formar o endereço completo do atributo que você deseja selecionar. Como um exemplo, se você fornece a lista <code>list("sales", 1L, "sale_id")</code> como input, você essencialmente está pedindo à função que extraia o atributo <code>"sale_id"</code> do primeiro elemento descrito em <code>"sales"</code>. Traduzindo isso para um código, supondo que essa lista esteja armazenada em um objeto chamado <code>recorded_sales</code>, podemos traduzir esse input para a seguinte seleção: <code>recorded_sales[["sales"]][[1]][["sale_id"]]</code>.</p>
<p>Vamos para um exemplo prático, usando dessa vez o objeto <code>recorded_sales</code>, o qual você pode importar para dentro da sua sessão usando os comandos abaixo. Esse objeto é uma lista de vendas feitas por cada loja (ou “franquia”) de uma firma hipotética. Em outras palavras, esse objeto contém uma lista com 2 lojas, e dentro de cada loja, temos uma lista das vendas feitas por essa loja específica.</p>
<p>Recomendo que você analise a estrutura dessa lista <code>recorded_sales</code> com calma, usando a função <code>str()</code> que introduzimos no capítulo 2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jsonlite)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>github <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/pedropark99/"</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>pasta <span class="ot">&lt;-</span> <span class="st">"Curso-R/master/Dados/"</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>arquivo <span class="ot">&lt;-</span> <span class="st">"recorded_sales.json"</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>recorded_sales <span class="ot">&lt;-</span> <span class="fu">read_json</span>(<span class="fu">paste0</span>(github, pasta, arquivo))</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>sales <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">store =</span> recorded_sales)</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>sales</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  store       
  &lt;named list&gt;
1 &lt;list [2]&gt;  </code></pre>
</div>
</div>
<p>No exemplo abaixo, estou usando <code>hoist()</code> para extrair dados específicos (<code>sale_id</code>, <code>value</code> e <code>currency</code>) da primeira venda (índice <code>1L</code>) feita por cada loja.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>sales <span class="sc">|&gt;</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest_longer</span>(store) <span class="sc">|&gt;</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hoist</span>(</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>    store,</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sale_id =</span> <span class="fu">list</span>(<span class="st">"sales"</span>, <span class="dv">1</span>L, <span class="st">"sales_id"</span>),</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">value =</span> <span class="fu">list</span>(<span class="st">"sales"</span>, <span class="dv">1</span>L, <span class="st">"value"</span>),</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">currency =</span> <span class="fu">list</span>(<span class="st">"sales"</span>, <span class="dv">1</span>L, <span class="st">"currency"</span>)</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  sale_id value currency store           
    &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;    &lt;list&gt;          
1       1  32.6 R$       &lt;named list [2]&gt;
2       4  21.5 R$       &lt;named list [2]&gt;</code></pre>
</div>
</div>
</section>
</section>
<section id="completando-e-expandindo-a-sua-tabela" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="completando-e-expandindo-a-sua-tabela"><span class="header-section-number">7.5</span> Completando e expandindo a sua tabela</h2>
<p>A operação que vou mostrar a seguir, serve para completar, ou inserir linhas que estão faltando em sua tabela. Em outras palavras, essa operação busca tornar os valores que estão implicitamente faltando em sua tabela, em valores não disponíveis explícitos. Você também pode enxergar esse processo, como uma forma rápida de expandir a sua tabela, a partir de combinações de valores. Um exemplo lógico do uso dessa operação, seriam datas que você gostaria que estivessem em sua tabela, mas que não se encontram nela no momento. Vamos supor por exemplo, que você possua a tabela abaixo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>dias <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"2020-09-01"</span>, <span class="st">"2020-09-05"</span>, <span class="st">"2020-09-07"</span>, <span class="st">"2020-09-10"</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>vendas <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">datas =</span> <span class="fu">as.Date</span>(dias),</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">nome =</span> <span class="fu">c</span>(<span class="st">"Ana"</span>, <span class="st">"Julia"</span>, <span class="st">"Joao"</span>, <span class="st">"Julia"</span>),</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">valor =</span> <span class="fu">rnorm</span>(<span class="dv">4</span>, <span class="at">mean =</span> <span class="dv">500</span>, <span class="at">sd =</span> <span class="dv">150</span>)</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>vendas</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  datas      nome  valor
  &lt;date&gt;     &lt;chr&gt; &lt;dbl&gt;
1 2020-09-01 Ana    406.
2 2020-09-05 Julia  528.
3 2020-09-07 Joao   375.
4 2020-09-10 Julia  739.</code></pre>
</div>
</div>
<p>Portanto, temos nessa tabela <code>vendas</code>, o nome de alguns vendedores e os valores de suas vendas efetuadas em alguns dias diferentes. No momento, temos vendas explícitas apenas nos dias 01, 05, 07 e 10 de setembro de 2020, mas o que ocorreu nos dias que estão entre essas datas (dias 02, 03, 04, 06, 08 e 09 de setembro de 2020)? Caso você estivesse apresentando esses dados para o seu chefe, por exemplo, essa seria uma questão que ele provavelmente faria a você. Bem, vamos supor que não tenham ocorrido vendas durante esses dias, e que por isso eles não estão sendo descritos na tabela <code>vendas</code>. Talvez seja de seu desejo, introduzir esses dias na tabela para que ninguém fique em dúvida a respeito desses dias. Com isso, precisamos então completar a tabela <code>vendas</code>, com linhas que estão implicitamente faltando nela.</p>
<section id="encontrando-possíveis-combinações-com-a-função-expand" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="encontrando-possíveis-combinações-com-a-função-expand"><span class="header-section-number">7.5.1</span> Encontrando possíveis combinações com a função <code>expand()</code></h3>
<p>Nessa seção, vamos introduzir alguns métodos para encontrarmos todas as combinações possíveis de seus dados. Pois isso é de certa forma um pré-requisito, ou um dos mecanismos por detrás do processo que desejamos aplicar sobre a tabela <code>vendas</code>.</p>
<p>Para calcular todas as combinações possíveis de seus dados, podemos utilizar a função <code>expand()</code> do pacote <code>tidyr</code>. Essa função busca expandir uma tabela, de forma que ela inclua todas as possíveis combinações de certos valores. Em maiores detalhes, essa função irá criar (com base nos dados que você fornecer a ela) uma nova tabela, ou um novo <code>tibble</code>, que irá incluir todas as combinações únicas e possíveis dos valores que você definiu. Portanto, se eu fornecer a tabela <code>vendas</code> à função, e pedir a ela que encontre todas as combinações possíveis entre os valores contidos nas colunas <code>datas</code> e <code>nomes</code>, esse será o resultado:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">expand</span>(vendas, datas, nome)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
  datas      nome 
  &lt;date&gt;     &lt;chr&gt;
1 2020-09-01 Ana  
2 2020-09-01 Joao 
3 2020-09-01 Julia
4 2020-09-05 Ana  
5 2020-09-05 Joao 
# ℹ 7 more rows</code></pre>
</div>
</div>
<p>Portanto, <code>expand()</code> irá criar uma nova tabela, contendo todas as possíveis combinações entre os valores das colunas <code>datas</code> e <code>nomes</code> da tabela <code>vendas</code>. Incluindo aquelas combinações que não aparecem na tabela inicial. Por exemplo, as combinações <code>(2020-09-01, Julia)</code>, ou <code>(2020-09-05, Joao)</code> e <code>(2020-09-10, Joao)</code> não estão presentes na tabela <code>vendas</code>, e mesmo assim foram introduzidas no resultado de <code>expand()</code>.</p>
<p>Porém, <code>expand()</code> não definiu novas combinações com as datas que estão faltando na tabela <code>vendas</code> (por exemplo, os dias 02, 03, 04 e 08 de setembro de 2020). Ou seja, em nenhum momento <code>expand()</code> irá adicionar algum dado à sua tabela, seja antes ou depois de encontrar todas as combinações únicas. Em outras palavras, <code>expand()</code> irá sempre encontrar todas as combinações possíveis, se baseando somente nos valores que já se encontram nas colunas que você forneceu a ela. Por isso, mesmo que a combinação <code>(2020-09-01, Julia)</code> não esteja definida na tabela <code>vendas</code>, ela é uma combinação possível, pois os valores <code>2020-09-01</code> e <code>Julia</code> estão presentes na tabela <code>vendas</code>.</p>
<p>Vale destacar, que você pode combinar as variáveis de sua tabela com vetores externos. Por exemplo, eu posso utilizar <code>seq.Date()</code> para gerar todas as datas que estão entre o dia 01 e 10 de setembro de 2020. No exemplo abaixo, perceba que <code>expand()</code> pega cada um dos 3 nomes únicos definidos na coluna <code>nome</code> de <code>vendas</code>, e combina eles com cada uma das 10 datas guardadas no vetor <code>vec_d</code>, gerando assim, uma nova tabela com 30 linhas (<span class="math inline">\(3\)</span> nomes <span class="math inline">\(\times 10\)</span> datas <span class="math inline">\(= 30\)</span> combinações).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>vec_d <span class="ot">&lt;-</span> <span class="fu">seq.Date</span>(<span class="fu">min</span>(vendas<span class="sc">$</span>datas), <span class="fu">max</span>(vendas<span class="sc">$</span>datas), <span class="at">by =</span> <span class="st">"day"</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">expand</span>(vendas, nome, vec_d)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 2
  nome  vec_d     
  &lt;chr&gt; &lt;date&gt;    
1 Ana   2020-09-01
2 Ana   2020-09-02
3 Ana   2020-09-03
4 Ana   2020-09-04
5 Ana   2020-09-05
# ℹ 25 more rows</code></pre>
</div>
</div>
<p>Além disso, a função <code>expand()</code> conta com uma função auxiliar útil (<code>nesting()</code>), que restringe quais combinações serão válidas para <code>expand()</code>. Ao incluir variáveis dentro da função <code>nesting()</code>, você está dizendo à <code>expand()</code>, que encontre apenas as combinações únicas (entre os valores dessas variáveis) que já estão presentes em sua base. Ou seja, se eu colocar as colunas <code>datas</code> e <code>nome</code> dentro de <code>nesting()</code>, a função <code>expand()</code> irá basicamente repetir a tabela <code>vendas</code>. Pois cada uma das 4 linhas (ou 4 combinações entre <code>datas</code> e <code>nome</code>), aparecem uma única vez nessa tabela.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">expand</span>(vendas, <span class="fu">nesting</span>(datas, nome))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  datas      nome 
  &lt;date&gt;     &lt;chr&gt;
1 2020-09-01 Ana  
2 2020-09-05 Julia
3 2020-09-07 Joao 
4 2020-09-10 Julia</code></pre>
</div>
</div>
<p>Dessa maneira, o uso de <code>nesting()</code> acima, é análogo ao uso da função <code>unique()</code> que vêm dos pacotes básicos do R. Logo, poderíamos atingir exatamente o mesmo resultado, utilizando qualquer uma das duas funções. Podemos por exemplo, adicionarmos uma quinta linha à tabela <code>vendas</code>, que repete os valores contidos na quarta linha da tabela. Se utilizarmos <code>unique()</code> ou <code>nesting()</code>, em ambos os casos, essa quinta linha repetida desaparece. Pois ambas as funções buscam encontrar todas as combinações <strong>únicas</strong> que aparecem ao longo da tabela <code>vendas</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>vendas[<span class="dv">5</span>, ] <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">as.Date</span>(<span class="st">"2020-09-10"</span>), <span class="st">"Julia"</span>, <span class="fl">739.29</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>vendas</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  datas      nome  valor
  &lt;date&gt;     &lt;chr&gt; &lt;dbl&gt;
1 2020-09-01 Ana    406.
2 2020-09-05 Julia  528.
3 2020-09-07 Joao   375.
4 2020-09-10 Julia  739.
5 2020-09-10 Julia  739.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># O mesmo resultado pode ser</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="co"># atingido com o uso de nesting() em expand()</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(vendas[ , <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  datas      nome 
  &lt;date&gt;     &lt;chr&gt;
1 2020-09-01 Ana  
2 2020-09-05 Julia
3 2020-09-07 Joao 
4 2020-09-10 Julia</code></pre>
</div>
</div>
<p>Vale destacar que você pode combinar o comportamento restrito e irrestrito de <code>expand()</code>. Ou seja, você pode restringir as combinações com o uso de <code>nesting()</code> para algumas variáveis, enquanto outras permanecem de fora dessa função, permitindo uma gama maior de combinações. No exemplo abaixo, <code>expand()</code> vai encontrar primeiro, cada combinação única entre <code>nome</code> e <code>valor</code> que está presente na tabela <code>vendas</code>, em seguida, a função irá encontrar <strong>todas</strong> as combinações possíveis entre as combinações anteriores (entre <code>nome</code> e <code>valor</code>) e todas as datas descritas na base.</p>
<p>Em outras palavras, nós podemos encontrar no resultado abaixo, uma combinação como <code>(2020-09-01, Julia, 528.)</code>. Pois a combinação <code>(Julia, 528.)</code> existe nas colunas <code>nome</code> e <code>valor</code> da tabela <code>vendas</code>, e como deixamos a coluna <code>datas</code> de fora de <code>nesting()</code>, <code>expand()</code> irá combinar <code>(Julia, 528.)</code> com toda e qualquer data disponível na tabela <code>vendas</code>.</p>
<p>Porém, nós não podemos encontrar no resultado abaixo, uma combinação como <code>(2020-09-01, Ana, 739.)</code>. Pois a única combinação entre as colunas <code>nome</code> e <code>valor</code>, presente na tabela <code>vendas</code>, que possui o valor 739 na coluna <code>valor</code>, é a linha que contém a combinação <code>(Julia, 739.)</code>. Logo, se não há nas colunas <code>nome</code> e <code>valor</code> alguma combinação entre <code>Ana</code> e o valor <code>739.</code>, <code>expand()</code> não irá combinar esses valores com todas as datas disponíveis na base. Pois as combinações entre as colunas <code>nome</code> e <code>valor</code> estão sendo restringidas por <code>nesting()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>vendas <span class="sc">%&gt;%</span> </span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand</span>(datas, <span class="fu">nesting</span>(nome, valor))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 3
  datas      nome  valor
  &lt;date&gt;     &lt;chr&gt; &lt;dbl&gt;
1 2020-09-01 Ana    406.
2 2020-09-01 Joao   375.
3 2020-09-01 Julia  528.
4 2020-09-01 Julia  739.
5 2020-09-05 Ana    406.
# ℹ 11 more rows</code></pre>
</div>
</div>
</section>
<section id="a-metodologia-por-detrás-do-processo" class="level3" data-number="7.5.2">
<h3 data-number="7.5.2" class="anchored" data-anchor-id="a-metodologia-por-detrás-do-processo"><span class="header-section-number">7.5.2</span> A metodologia por detrás do processo</h3>
<p>Apesar de próximo, a função <code>expand()</code> não é suficiente para produzirmos o resultado que desejamos sobre a tabela <code>vendas</code>. Lembre-se que desejamos completar essa tabela com os dados referentes aos dias 02, 03, 04, 06, 08 e 09 de setembro de 2020, que estão “em teoria” faltando nessa tabela.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>vendas</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  datas      nome  valor
  &lt;date&gt;     &lt;chr&gt; &lt;dbl&gt;
1 2020-09-01 Ana    406.
2 2020-09-05 Julia  528.
3 2020-09-07 Joao   375.
4 2020-09-10 Julia  739.</code></pre>
</div>
</div>
<p>Primeiro, precisamos encontrar todos valores possíveis da variável que está incompleta na tabela <code>vendas</code>. Ou seja, queremos encontrar todas as datas possíveis entre os dias 01 e 10 de setembro de 2020, pois esses dias são os limites da tabela. Para isso, podemos utilizar a função <code>seq.Date()</code> em conjunto com <code>tibble()</code>. Dessa forma, nos criamos uma nova tabela, que contém uma sequência de datas que vai do dia 01 até o dia 10 de setembro. O mesmo resultado, poderia ser atingido, caso utilizássemos <code>seq.Date()</code> dentro de <code>expand()</code>, já que <code>expand()</code> cria por padrão uma nova tabela com todas as combinações possíveis dos dados que você fornece a ela.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>nova_tab <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">datas =</span> <span class="fu">seq.Date</span>(<span class="fu">min</span>(vendas<span class="sc">$</span>datas), <span class="fu">max</span>(vendas<span class="sc">$</span>datas), <span class="at">by =</span> <span class="st">"day"</span>)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>nova_tab</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 1
  datas     
  &lt;date&gt;    
1 2020-09-01
2 2020-09-02
3 2020-09-03
4 2020-09-04
5 2020-09-05
# ℹ 5 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># O mesmo resultado poderia ser atingido com:</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>nova_tab <span class="ot">&lt;-</span> <span class="fu">expand</span>(</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">datas =</span> <span class="fu">seq.Date</span>(<span class="fu">min</span>(vendas<span class="sc">$</span>datas), <span class="fu">max</span>(vendas<span class="sc">$</span>datas), <span class="at">by =</span> <span class="st">"day"</span>)</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Em seguida, podemos utilizar a função <code>full_join()</code><a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> do pacote <code>dplyr</code>, para trazermos os dados disponíveis na tabela <code>vendas</code> para essa nova tabela <code>nova_tab</code>. Agora, nós temos uma nova tabela, que contém todos os dados que já estão definidos na tabela <code>vendas</code>, além dos dias que estavam faltando anteriormente, e que agora também estão definidos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>nova_tab <span class="ot">&lt;-</span> nova_tab <span class="sc">%&gt;%</span> </span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">full_join</span>(vendas, <span class="at">by =</span> <span class="st">"datas"</span>)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>nova_tab</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
  datas      nome  valor
  &lt;date&gt;     &lt;chr&gt; &lt;dbl&gt;
1 2020-09-01 Ana    406.
2 2020-09-02 &lt;NA&gt;    NA 
3 2020-09-03 &lt;NA&gt;    NA 
4 2020-09-04 &lt;NA&gt;    NA 
5 2020-09-05 Julia  528.
# ℹ 5 more rows</code></pre>
</div>
</div>
<p>O que resta agora, é preenchermos os campos com valores não-disponíveis (<code>NA</code>) com algum outro valor que seja mais claro, ou que indique de uma forma melhor, que não houve vendas realizadas naquele dia. Visando esse objetivo, temos a função <code>replace_na()</code> do pacote <code>tidyr</code>. Nessa função, você irá fornecer uma lista (<code>list()</code>) contendo os valores que vão substituir os valores <code>NA</code> em cada coluna de sua tabela. Essa lista precisa ser nomeada. Basta nomear cada valor substituto com o nome da coluna em que você deseja utilizar esse valor. Logo, se eu quero substituir todos os valores <code>NA</code> na coluna <code>valor</code>, por um zero, basta eu nomear esse zero com o nome dessa coluna, dentro da lista (<code>list()</code>) que eu forneci à <code>replace_na()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>nova_tab <span class="sc">%&gt;%</span> </span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">replace_na</span>(</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">list</span>(<span class="at">nome =</span> <span class="st">"Não houve vendas"</span>, <span class="at">valor =</span> <span class="dv">0</span>)</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
  datas      nome             valor
  &lt;date&gt;     &lt;chr&gt;            &lt;dbl&gt;
1 2020-09-01 Ana               406.
2 2020-09-02 Não houve vendas    0 
3 2020-09-03 Não houve vendas    0 
4 2020-09-04 Não houve vendas    0 
5 2020-09-05 Julia             528.
# ℹ 5 more rows</code></pre>
</div>
</div>
</section>
<section id="a-função-complete-como-um-atalho-útil" class="level3" data-number="7.5.3">
<h3 data-number="7.5.3" class="anchored" data-anchor-id="a-função-complete-como-um-atalho-útil"><span class="header-section-number">7.5.3</span> A função <code>complete()</code> como um atalho útil</h3>
<p>A função <code>complete()</code> é um <em>wrapper</em>, ou uma função auxiliar do pacote <code>tidyr</code>, que engloba as funções <code>expand()</code>, <code>full_join()</code>, e <code>replace_na()</code>. Ou seja, a função <code>complete()</code> é um atalho para aplicarmos a metodologia que acabamos de descrever na seção anterior. A função possui três argumentos principais: 1) <code>data</code>, o nome do objeto onde a sua tabela está salva; 2) <code>...</code>, a especificação das colunas a serem completadas, ou “expandidas” por <code>complete()</code>; 3) <code>fill</code>, uma lista nomeada (como a que fornecemos em <code>replace_na()</code>), que atribui para cada variável (ou coluna) de sua tabela, um valor a ser utilizado (ao invés de <code>NA</code>) para as combinações faltantes.</p>
<p>Vou explicar o argumento <code>fill</code> mais a frente, por isso, vamos nos concentrar nos outros dois. A tabela que contém os nossos dados se chama <code>vendas</code>, e por isso, é esse valor que devemos atribuir ao argumento <code>data</code>. Porém, como estamos utilizando o <em>pipe</em> (<code>%&gt;%</code>) no exemplo abaixo, ele já está realizando esse serviço para nós. Já o segundo argumento (<code>...</code>), diz respeita a lista de especificações que vão definir como a função <code>complete()</code> deve completar cada coluna da nossa tabela.</p>
<p>Em outras palavras, o segundo argumento (<code>...</code>) é a parte da função <code>complete()</code> que diz respeito ao uso de <code>expand()</code>. Você deve, portanto, preencher este argumento, da mesma forma que você faria com a função <code>expand()</code>. No exemplo abaixo, o primeiro argumento (<code>data</code>), já está sendo definido pelo operador <em>pipe</em> (<code>%&gt;%</code>). Perceba que eu preencho a função <code>complete()</code>, da mesma forma em que preenchi a função <code>expand()</code> na seção anterior. Perceba também, que <code>complete()</code> já me retorna como resultado, a tabela expandida após o uso de <code>full_join()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>vendas <span class="sc">%&gt;%</span> </span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">complete</span>(</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">datas =</span> <span class="fu">seq.Date</span>(<span class="fu">min</span>(datas), <span class="fu">max</span>(datas), <span class="at">by =</span> <span class="st">"day"</span>)</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
  datas      nome  valor
  &lt;date&gt;     &lt;chr&gt; &lt;dbl&gt;
1 2020-09-01 Ana    406.
2 2020-09-02 &lt;NA&gt;    NA 
3 2020-09-03 &lt;NA&gt;    NA 
4 2020-09-04 &lt;NA&gt;    NA 
5 2020-09-05 Julia  528.
# ℹ 5 more rows</code></pre>
</div>
</div>
<p>O último passo que resta agora, seria o uso de <code>replace_na()</code> para preencher os valores não-disponíveis por algum outro valor mais claro. Nós ainda podemos utilizar a função <code>complete()</code> para executarmos esse passo. Basta você fornecer à <code>complete()</code> através de seu terceiro argumento (<code>fill</code>), a mesma lista que você forneceria à <code>replace_na()</code>. Dessa forma, temos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>vendas <span class="sc">%&gt;%</span> </span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">complete</span>(</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">datas =</span> <span class="fu">seq.Date</span>(<span class="fu">min</span>(datas), <span class="fu">max</span>(datas), <span class="at">by =</span> <span class="st">"day"</span>),</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="fu">list</span>(<span class="at">nome =</span> <span class="st">"Não houve vendas"</span>, <span class="at">valor =</span> <span class="dv">0</span>)</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
  datas      nome             valor
  &lt;date&gt;     &lt;chr&gt;            &lt;dbl&gt;
1 2020-09-01 Ana               406.
2 2020-09-02 Não houve vendas    0 
3 2020-09-03 Não houve vendas    0 
4 2020-09-04 Não houve vendas    0 
5 2020-09-05 Julia             528.
# ℹ 5 more rows</code></pre>
</div>
</div>
</section>
</section>
<section id="preenchendo-valores-não-disponíveis-na" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="preenchendo-valores-não-disponíveis-na"><span class="header-section-number">7.6</span> Preenchendo valores não-disponíveis (<code>NA</code>)</h2>
<section id="utilizando-se-de-valores-anteriores-ou-posteriores" class="level3" data-number="7.6.1">
<h3 data-number="7.6.1" class="anchored" data-anchor-id="utilizando-se-de-valores-anteriores-ou-posteriores"><span class="header-section-number">7.6.1</span> Utilizando-se de valores anteriores ou posteriores</h3>
<p>As operações que vou mostrar a seguir, servem para preencher linhas com dados não-disponíveis (<code>NA</code>), com valores anteriores ou posteriores que estão disponíveis em sua tabela. Vamos começar com um exemplo simples através da tabela <code>df</code>, que você pode criar em seu R utilizando os comandos abaixo. Nessa tabela, temos algumas vendas anuais hipotéticas. Agora, perceba que por algum motivo, o ano em que as vendas ocorreram, só foram guardadas na primeira linha de cada ID (<code>id</code>). Isso é algo que devemos corrigir nessa tabela.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="dv">2001</span><span class="sc">:</span><span class="dv">2004</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="at">each =</span> <span class="dv">3</span>),</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ano =</span> <span class="cn">NA_real_</span>,</span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">valor =</span> <span class="fu">rnorm</span>(<span class="dv">12</span>, <span class="at">mean =</span> <span class="dv">1000</span>, <span class="at">sd =</span> <span class="dv">560</span>)</span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a>df[<span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">12</span>, <span class="at">by =</span> <span class="dv">3</span>), <span class="st">"ano"</span>] <span class="ot">&lt;-</span> v</span>
<span id="cb83-11"><a href="#cb83-11" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
     id   ano valor
  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1  2001  649.
2     1    NA 1103.
3     1    NA  532.
4     2  2002 1893.
5     2    NA 1185.
# ℹ 7 more rows</code></pre>
</div>
</div>
<p>Portanto, o que queremos fazer, é completar as linhas de <code>NA</code>’s, com o ano correspondente a essas vendas. Pelo fato dos anos estarem separados por um número constante de linhas, ou seja, a cada 3 linhas de <code>NA</code>’s, temos um novo ano, podemos pensar em algumas soluções relativamente simples como a definida abaixo. Porém, a simplicidade do problema, depende dos intervalos entre cada valor, serem constantes. A partir do momento em que esses valores começarem a se dispersar em distâncias inconsistentes, uma solução como a definida abaixo, não servirá.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>niveis <span class="ot">&lt;-</span> <span class="fu">unique</span>(df<span class="sc">$</span>ano)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>niveis <span class="ot">&lt;-</span> niveis[<span class="sc">!</span><span class="fu">is.na</span>(niveis)]</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>repair_vec <span class="ot">&lt;-</span> df<span class="sc">$</span>ano</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>repair_vec[<span class="fu">is.na</span>(repair_vec)] <span class="ot">&lt;-</span> <span class="fu">rep</span>(niveis, <span class="at">each =</span> <span class="dv">2</span>)</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>ano <span class="ot">&lt;-</span> repair_vec</span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
     id   ano valor
  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1  2001  649.
2     1  2001 1103.
3     1  2001  532.
4     2  2002 1893.
5     2  2002 1185.
# ℹ 7 more rows</code></pre>
</div>
</div>
<p>Apesar de ser um problema simples, podemos alcançar uma solução ainda mais simples, ao utilizarmos funções que são especializadas nesses problemas. Esse é o caso da função <code>fill()</code> do pacote <code>tidyr</code>, que foi criada justamente para esse propósito. Portanto, sempre que você possuir em sua tabela, uma coluna onde você deseja substituir uma sequência de <code>NA</code>’s pelo último (ou próximo) valor disponível, você pode utilizar essa função para tal tarefa.</p>
<p>A função <code>fill()</code> possui três argumentos: 1) <code>data</code>, o objeto onde a tabela com que deseja trabalhar, está salva; 2) <code>...</code>, a lista de colunas em que você deseja aplicar a função; 3) <code>.direction</code>, define a direção que a função deve seguir na hora de preencher os valores.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">fill</span>(ano)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
     id   ano valor
  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1  2001  649.
2     1  2001 1103.
3     1  2001  532.
4     2  2002 1893.
5     2  2002 1185.
# ℹ 7 more rows</code></pre>
</div>
</div>
<p>A função <code>fill()</code> trabalha a partir de uma dada direção vertical em sua tabela. Por padrão, a função <code>fill()</code> irá preencher os valores indo para baixo, ou seja, partindo do topo da tabela, até a sua base. Logo, a função irá substituir qualquer <code>NA</code> com o último valor disponível, ou em outras palavras, com o valor disponível anterior ao <code>NA</code> em questão. A função lhe oferece o argumento <code>.direction</code>, caso você deseja alterar esse comportamento. Logo, se você deseja preencher esses valores <code>NA</code>’s com o próximo valor disponível em relação ao <code>NA</code> em questão. Isto é, preencher os valores para cima, partindo da base da tabela, e seguindo para o seu topo. Você precisa definir o argumento da seguinte maneira:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">fill</span>(ano, <span class="at">.direction =</span> <span class="st">"up"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
     id   ano valor
  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1  2001  649.
2     1  2002 1103.
3     1  2002  532.
4     2  2002 1893.
5     2  2003 1185.
# ℹ 7 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Caso prefira não utilizar o pipe ( %&gt;% ),</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ficaria dessa forma:</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a><span class="co"># fill(df, ano, .direction = "up")</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Portanto, se tivéssemos que colocar essas operações em uma representação visual, teríamos algo como a <a href="#fig-fill-tidy" class="quarto-xref">Figura&nbsp;<span>7.4</span></a>. Lembrando que a função usa por padrão, a direção <em>down</em>, logo, no primeiro caso mostrado na <a href="#fig-fill-tidy" class="quarto-xref">Figura&nbsp;<span>7.4</span></a>, você não precisaria definir explicitamente o argumento <code>.direction</code>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-fill-tidy" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fill-tidy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./../Figuras/fill_1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fill-tidy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7.4: Representação do processo executado pela função <code>fill</code>
</figcaption>
</figure>
</div>
</div>
</div>
<p>Apesar de serem os exemplos mais claros de aplicação, serão raras as ocasiões em que você terá esse problema posto claramente já de início em sua tabela. Com isso, eu quero dizer que serão raros os momentos em que você desde o início terá uma tabela, onde por algum motivo, os registros aparecem apenas na primeira (ou na última) linha que diz respeito aquele registro.</p>
<p>Usualmente, você irá utilizar a função <code>fill()</code> quando você já estiver realizando diversas outras transformações em sua tabela, para se chegar aonde deseja. Um exemplo claro dessa ideia, seria uma tabela onde os valores são registrados no primeiro dia de cada semana (basicamente você possui dados semanais), mas você precisa calcular uma média móvel diária. Isso significa que para calcular essa média móvel, você teria que completar os dias faltantes de cada semana, e ainda utilizar o <code>fill()</code> para transportar o valor do primeiro dia, para os dias restantes da semana.</p>
<p>Vale ressaltar, que você pode utilizar em <code>fill()</code>, todos os mecanismos de seleção que introduzimos em <code>select()</code>, para selecionar as colunas em que você deseja aplicar a função <code>fill()</code>. Isso também significa, que com <code>fill()</code> você pode preencher várias colunas ao mesmo tempo. Agora, para relembrarmos esses mecanismos, vamos criar uma tabela inicialmente vazia, que contém o total de vendas realizadas nos 6 primeiros meses de 2020, por cada funcionário de uma loja.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2</span>)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>funcionarios <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">mes =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">times =</span> <span class="dv">4</span>),</span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">vendas =</span> <span class="fu">floor</span>(<span class="fu">rnorm</span>(<span class="dv">24</span>, <span class="at">mean =</span> <span class="dv">60</span>, <span class="at">sd =</span> <span class="dv">24</span>)),</span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">nome =</span> <span class="cn">NA_character_</span>,</span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">salario =</span> <span class="cn">NA_real_</span>,</span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">mes_ent =</span> <span class="cn">NA_real_</span>,</span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">ano_ent =</span> <span class="cn">NA_real_</span>,</span>
<span id="cb92-9"><a href="#cb92-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">unidade =</span> <span class="cn">NA_character_</span></span>
<span id="cb92-10"><a href="#cb92-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb92-11"><a href="#cb92-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-12"><a href="#cb92-12" aria-hidden="true" tabindex="-1"></a>funcionarios</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 7
    mes vendas nome  salario mes_ent ano_ent unidade
  &lt;int&gt;  &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;  
1     1     38 &lt;NA&gt;       NA      NA      NA &lt;NA&gt;   
2     2     64 &lt;NA&gt;       NA      NA      NA &lt;NA&gt;   
3     3     98 &lt;NA&gt;       NA      NA      NA &lt;NA&gt;   
4     4     32 &lt;NA&gt;       NA      NA      NA &lt;NA&gt;   
5     5     58 &lt;NA&gt;       NA      NA      NA &lt;NA&gt;   
# ℹ 19 more rows</code></pre>
</div>
</div>
<p>Em seguida, vamos preencher as colunas vazias (<code>nome</code>, <code>salario</code>, <code>mes_ent</code>, …) de forma com que as informações de cada vendedor, apareçam apenas na última linha que diz respeito aquele vendedor. Como exemplo, as informações do vendedor Henrique, aparecem apenas na sexta linha da tabela, que é a última linha da tabela que se refere a ele.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>valores <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">salario =</span> <span class="fu">c</span>(<span class="dv">1560</span>, <span class="dv">2120</span>, <span class="dv">1745</span>, <span class="dv">1890</span>),</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">nome =</span> <span class="fu">c</span>(<span class="st">"Henrique"</span>, <span class="st">"Ana"</span>, <span class="st">"João"</span>, <span class="st">"Milena"</span>),</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">ano_ent =</span> <span class="fu">c</span>(<span class="dv">2000</span>, <span class="dv">2001</span>, <span class="dv">2010</span>, <span class="dv">2015</span>),</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">mes_ent =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">10</span>, <span class="dv">5</span>, <span class="dv">8</span>),</span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">unidade =</span> <span class="fu">c</span>(<span class="st">"Afonso Pena"</span>, <span class="st">"Savassi"</span>, <span class="st">"São Paulo"</span>, <span class="st">"Amazonas"</span>)</span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a>colunas <span class="ot">&lt;-</span> <span class="fu">colnames</span>(funcionarios)[<span class="dv">3</span><span class="sc">:</span><span class="dv">7</span>]</span>
<span id="cb94-10"><a href="#cb94-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> colunas){</span>
<span id="cb94-11"><a href="#cb94-11" aria-hidden="true" tabindex="-1"></a>  funcionarios[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span> <span class="sc">*</span> <span class="dv">6</span>, i] <span class="ot">&lt;-</span> valores[[i]]</span>
<span id="cb94-12"><a href="#cb94-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb94-13"><a href="#cb94-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Com isso, temos o seguinte resultado:</span></span>
<span id="cb94-14"><a href="#cb94-14" aria-hidden="true" tabindex="-1"></a>funcionarios <span class="sc">%&gt;%</span> <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">12</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 7
     mes vendas nome     salario mes_ent ano_ent unidade    
   &lt;int&gt;  &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      
 1     1     38 &lt;NA&gt;          NA      NA      NA &lt;NA&gt;       
 2     2     64 &lt;NA&gt;          NA      NA      NA &lt;NA&gt;       
 3     3     98 &lt;NA&gt;          NA      NA      NA &lt;NA&gt;       
 4     4     32 &lt;NA&gt;          NA      NA      NA &lt;NA&gt;       
 5     5     58 &lt;NA&gt;          NA      NA      NA &lt;NA&gt;       
 6     6     63 Henrique    1560       2    2000 Afonso Pena
 7     1     76 &lt;NA&gt;          NA      NA      NA &lt;NA&gt;       
 8     2     54 &lt;NA&gt;          NA      NA      NA &lt;NA&gt;       
 9     3    107 &lt;NA&gt;          NA      NA      NA &lt;NA&gt;       
10     4     56 &lt;NA&gt;          NA      NA      NA &lt;NA&gt;       
11     5     70 &lt;NA&gt;          NA      NA      NA &lt;NA&gt;       
12     6     83 Ana         2120      10    2001 Savassi    
# ℹ 12 more rows</code></pre>
</div>
</div>
<p>Portanto, o que precisamos é aplicar a função <code>fill()</code> usando <code>.direction = "up"</code>, em cada uma dessas colunas vazias, de forma a preencher o restante das linhas com as informações de cada vendedor. Dada a natureza dessa tabela, os dois melhores mecanismos que aprendemos em <code>select()</code>, para selecionarmos essas colunas vazias, são: 1) usar os índices dessas colunas; 2) nos basearmos nos tipos de dados contidos em cada coluna; 3) usar um vetor externo com os nomes das colunas que desejamos.</p>
<p>Para utilizar o método 3 que citei acima, podemos utilizar o vetor <code>colunas</code> que criamos agora a pouco ao preenchermos a tabela, e já contém os nomes das colunas que desejamos. Porém, para o exemplo abaixo do método 2, você talvez se pergunte: “Se estamos aplicando a função <code>fill()</code> sobre todas as colunas que contém ou dados de texto (<code>character</code>), ou dados numéricos (<code>numeric</code>), nós também estamos aplicando a função sobre as colunas <code>mes</code> e <code>vendas</code>, das quais não necessitam de ajuste. O que acontece?”. Nada irá ocorrer com as colunas <code>mes</code> e <code>vendas</code>, caso elas já estejam corretamente preenchidas, portanto, podemos aplicar a função sobre elas sem medo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Todas as três alternativas abaixo</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="co"># geram o mesmo resultado:</span></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>funcionarios <span class="sc">%&gt;%</span> </span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fill</span>(</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>    <span class="dv">3</span><span class="sc">:</span><span class="dv">7</span>,</span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">.direction =</span> <span class="st">"up"</span></span>
<span id="cb96-7"><a href="#cb96-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb96-8"><a href="#cb96-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-9"><a href="#cb96-9" aria-hidden="true" tabindex="-1"></a>funcionarios <span class="sc">%&gt;%</span> </span>
<span id="cb96-10"><a href="#cb96-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fill</span>(</span>
<span id="cb96-11"><a href="#cb96-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">all_of</span>(colunas),</span>
<span id="cb96-12"><a href="#cb96-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">.direction =</span> <span class="st">"up"</span></span>
<span id="cb96-13"><a href="#cb96-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>funcionarios <span class="sc">%&gt;%</span> </span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fill</span>(</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">where</span>(is.character),</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">where</span>(is.numeric),</span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">.direction =</span> <span class="st">"up"</span></span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 24 × 7
    mes vendas nome     salario mes_ent ano_ent unidade    
  &lt;int&gt;  &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      
1     1     38 Henrique    1560       2    2000 Afonso Pena
2     2     64 Henrique    1560       2    2000 Afonso Pena
3     3     98 Henrique    1560       2    2000 Afonso Pena
4     4     32 Henrique    1560       2    2000 Afonso Pena
5     5     58 Henrique    1560       2    2000 Afonso Pena
# ℹ 19 more rows</code></pre>
</div>
</div>


<div id="refs" class="references csl-bib-body" data-entry-spacing="1" role="list">
<div id="ref-wickham2014" class="csl-entry" role="listitem">
WICKHAM, H. <a href="http://www.jstatsoft.org/v59/i10/">Tidy Data</a>. <strong>The Journal of Statistical Software</strong>, v. 59, 2014.
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Esses são termos comuns na comunidade de R, mas estes formatos também são conhecidos, ou chamados por <em>indexed data</em> (<em>long</em>) e por <em>cartesian data</em> (<em>wide</em>).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Apesar de serem um caso raro no R, as tabelas que possuem listas como colunas, tem se tornado cada vez mais comuns ao longo de diversas análises, e são comumente chamadas pela comunidade de <em>nested tables</em>, ou de <em>nested data</em>. Alguns pacotes tem se desenvolvido, de maneira muito forte nessa área, e por isso, essas estruturas tem se tornado de grande utilidade em diversas aplicações. Alguns desses pacotes incluem o próprio <code>tidyr</code>, além do pacote <code>broom</code>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>https://www.youtube.com/watch?v=rz3_FDVt9eg&amp;ab_channel=PsychologyattheUniversityofEdinburgh<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Caso você não conheça a função <code>full_join()</code>, lembre-se que ela é descrita em detalhes no capítulo “Introdução a base de dados relacionais”.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../Capítulos/06-dados-relacionais.html" class="pagination-link" aria-label="Introdução a base de dados relacionais com `dplyr`">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introdução a base de dados relacionais com <code>dplyr</code></span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../Capítulos/08-ggplot.html" class="pagination-link" aria-label="Visualização de dados com `ggplot2`">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Visualização de dados com <code>ggplot2</code></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>